"""Endpoint tests for GET /api/audit/events (dmfdeploy/dmfdeploy#496 plan).

The four discriminator users from plan §7 AC 5a: a generic allowed/denied
pair cannot tell a per-class gate from a single-gate implementation, so the
fixture below carries every covered class and every excluded class, and the
expected set per user is enumerated here literally — never computed by
calling classify_record/user_passes_gate against this same fixture (that
would be exactly the tautology AC 5a rules out).
"""

from __future__ import annotations

import logging

from fastapi.testclient import TestClient
import pytest

import dmf_cms.audit_events as audit_events
from dmf_cms.main import _audit_awx_write, create_app
from dmf_cms.security import UserIdentity
from dmf_cms.settings import LokiSettings, Settings


OPERATOR_ONLY = ("dmf-console-operator",)
VIEWER_IN_MEDIA_ENGINEERS = ("dmf-console-viewer", "media-engineers")
OPERATOR_IN_MEDIA_ENGINEERS = ("dmf-console-operator", "media-engineers")
VIEWER_ONLY = ("dmf-console-viewer",)


def _client(groups, *, loki_configured=True) -> TestClient:
    settings = Settings(
        runtime_mode="local",
        dev_login_enabled=True,
        dev_groups=groups,
        loki=LokiSettings(url="http://loki.test") if loki_configured else LokiSettings(),
    )
    client = TestClient(create_app(settings=settings))
    client.get("/auth/login", follow_redirects=False)  # dev login -> session
    return client


def _line(
    *, action, actor, role, request_id, target, reason, outcome,
    workload="", capacity="", linked_request_id=None,
) -> str:
    # dmfdeploy/dmf-cms#140: the fmt=2 grammar -- target/actor/reason/
    # workload/capacity are quoted (%r), exactly as the real emitter
    # writes them; action/role/real_role/request_id/outcome stay plain.
    line = (
        f"awx write: fmt=2 action={action} actor={actor!r} role={role} real_role= "
        f"request_id={request_id} target={target!r} reason={reason!r} "
        f"outcome={outcome} workload={workload!r} capacity={capacity!r}"
    )
    if linked_request_id is not None:
        line += f" linked_request_id={linked_request_id}"
    return "2026-09-03 12:00:00,000 INFO dmf_cms.audit: " + line


# The fixture — every covered class, every excluded class, a real
# auto-rollback join pair, an auto-rollback whose parent does not resolve
# (degrade-not-drop), an unrecognised action, and an unparseable line.
# Enumerated by hand; never generated by calling the code under test.
DEPLOY = _line(
    action="deploy", actor="alice", role="operator", request_id="rid-deploy-1",
    target="wl-a", reason="demo deploy", outcome="dispatched", workload="wl-a",
)
DEPLOY_REFUSED = _line(
    action="deploy", actor="alice", role="operator", request_id="rid-deploy-2",
    target="wl-a", reason="demo deploy retry", outcome="facility-busy",
)
TEARDOWN = _line(
    action="teardown", actor="alice", role="operator", request_id="rid-teardown-1",
    target="wl-b", reason="demo teardown", outcome="dispatched",
)
SWITCH_SOURCE = _line(
    action="switch-source", actor="bob", role="engineer", request_id="rid-switch-1",
    target="receiver-1", reason="demo switch", outcome="active", workload="src-1",
)
AUTO_ROLLBACK = _line(
    action="rollback", actor="system:auto-rollback", role="system", request_id="rid-autorb-1",
    target="run-123", reason="auto: deploy wl-a failed after start (failed_rollback_required)",
    outcome="auto-triggered", linked_request_id="rid-deploy-1",
)
AUTO_ROLLBACK_ORPHAN = _line(
    action="rollback", actor="system:auto-rollback", role="system", request_id="rid-autorb-2",
    target="run-999", reason="auto: deploy wl-z failed after start (failed_rollback_required)",
    outcome="auto-triggered", linked_request_id="rid-nonexistent-parent",
)
FINALISE_PURGE = _line(
    action="finalise-purge", actor="carol", role="operator", request_id="rid-purge-1",
    target="slug-x", reason="demo purge", outcome="dispatched",
)
LAUNCH = _line(
    action="launch", actor="dave", role="engineer", request_id="rid-launch-1",
    target="some-jt", reason="demo launch", outcome="dispatched",
)
VERIFY_DRAIN = _line(
    action="verify-drain", actor="alice", role="operator", request_id="rid-drain-1",
    target="run-456", reason="demo drain", outcome="dispatched",
)
OPERATOR_ROLLBACK = _line(
    action="rollback", actor="alice", role="operator", request_id="rid-oprb-1",
    target="run-789", reason="demo manual rollback", outcome="dispatched",
)
UNRECOGNISED_ACTION = _line(
    action="mystery-action", actor="alice", role="operator", request_id="rid-mystery-1",
    target="wl-a", reason="should never appear", outcome="dispatched",
)
UNPARSEABLE = "2026-09-03 12:00:00,000 INFO dmf_cms.audit: awx write: action=deploy actor=alice request_id=rid-broken"
# dmfdeploy/dmf-cms#140: legacy is dropped, not parsed by a fallback
# grammar (operator decision) — so a truncated/malformed line, WITH or
# WITHOUT a truncated fmt=2 marker, is unparseable for the same reason
# UNPARSEABLE above already is, and needs no dedicated fixture. What DOES
# still need coverage on the new format: codex R496-C P1-2's property
# that a genuinely blank `outcome` value (the row otherwise complete and
# well-formed) renders as an honest "unknown", never a forged verdict —
# reachable on this grammar as an outcome that's simply empty, not as a
# truncation (any truncation of a REQUIRED field now drops the whole row
# — there is no partial-render fallback left to test).
DEPLOY_BLANK_OUTCOME = _line(
    action="deploy", actor="erin", role="operator", request_id="rid-deploy-corrupted",
    target="wl-c", reason="outcome field lost upstream", outcome="",
)

FIXTURE_LINES = [
    DEPLOY, DEPLOY_REFUSED, TEARDOWN, SWITCH_SOURCE, AUTO_ROLLBACK, AUTO_ROLLBACK_ORPHAN,
    FINALISE_PURGE, LAUNCH, VERIFY_DRAIN, OPERATOR_ROLLBACK, UNRECOGNISED_ACTION, UNPARSEABLE,
    DEPLOY_BLANK_OUTCOME,
]

_VALID_RETENTION_CONFIG = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
"""


def _fake_query_range(*, url, selector, start_ns, end_ns, limit, timeout=10):
    # Plan §4.1: content match, never a logger-field filter — the
    # auto-rollback line is on the module logger, not the audit child
    # logger, so a logger= filter would silently drop a covered class.
    assert '|= "awx write:"' in selector
    assert "logger=" not in selector
    return [{"stream": {}, "values": [[str(i), line] for i, line in enumerate(FIXTURE_LINES)]}]


def _fake_raw_runtime_config(*, url, timeout=10):
    return _VALID_RETENTION_CONFIG


@pytest.fixture(autouse=True)
def _loki(monkeypatch):
    monkeypatch.setattr(audit_events.loki, "query_range", _fake_query_range)
    monkeypatch.setattr(audit_events.loki, "raw_runtime_config", _fake_raw_runtime_config)


def _event_ids(payload) -> set[str]:
    return {e["request_id"] for e in payload["events"]}


# ----------------------------------------------------------------------
# AC 5a — the four discriminator users, equality, not subset/superset.
# ----------------------------------------------------------------------

def test_operator_not_in_media_engineers_sees_deploy_teardown_rollback_not_switch():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert _event_ids(payload) == {
        "rid-deploy-1", "rid-deploy-2", "rid-teardown-1", "rid-autorb-1", "rid-autorb-2",
        "rid-deploy-corrupted",
    }


def test_viewer_in_media_engineers_sees_only_switch_source():
    client = _client(VIEWER_IN_MEDIA_ENGINEERS)
    payload = client.get("/api/audit/events").json()
    assert _event_ids(payload) == {"rid-switch-1"}


def test_operator_in_media_engineers_sees_every_covered_row():
    client = _client(OPERATOR_IN_MEDIA_ENGINEERS)
    payload = client.get("/api/audit/events").json()
    assert _event_ids(payload) == {
        "rid-deploy-1", "rid-deploy-2", "rid-teardown-1", "rid-autorb-1", "rid-autorb-2", "rid-switch-1",
        "rid-deploy-corrupted",
    }


def test_viewer_qualifying_for_neither_sees_the_empty_set():
    client = _client(VIEWER_ONLY)
    payload = client.get("/api/audit/events").json()
    assert _event_ids(payload) == set()


def test_excluded_rows_never_appear_even_for_the_most_privileged_user():
    client = _client(OPERATOR_IN_MEDIA_ENGINEERS)
    payload = client.get("/api/audit/events").json()
    ids = _event_ids(payload)
    for excluded_id in ("rid-purge-1", "rid-launch-1", "rid-drain-1", "rid-oprb-1", "rid-mystery-1", "rid-broken"):
        assert excluded_id not in ids


def test_disclosure_names_the_two_exclusion_reasons_distinctly():
    client = _client(VIEWER_ONLY)
    payload = client.get("/api/audit/events").json()
    by_class = {row["class"]: row["reason"] for row in payload["excluded"]}
    assert by_class["finalise-purge"] == "access"
    assert by_class["launch"] == "scope"
    assert by_class["verify-drain"] == "scope"
    assert by_class["rollback"] == "scope"


# ----------------------------------------------------------------------
# AC 3 / AC 5b — auto-rollback: presence unconditional, label conditional.
# ----------------------------------------------------------------------

def test_auto_rollback_carries_its_parents_workload_when_the_parent_resolves():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-autorb-1")
    assert row["workload"] == "wl-a"
    assert row["outcome"]["state"] == "in_flight"


def test_auto_rollback_still_renders_with_no_workload_when_the_parent_does_not_resolve():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-autorb-2")
    assert row["workload"] is None  # degraded label, NOT a dropped row


# ----------------------------------------------------------------------
# Outcome rendering (AC 2 / AC 2a).
# ----------------------------------------------------------------------

def test_a_refusal_overrides_watched_acceptance_and_never_leaks_raw_at_default():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-deploy-2")
    assert row["outcome"]["state"] == "failed"
    assert row["outcome"]["detail"] == "facility-busy"
    assert "facility-busy" not in row["outcome"]["headline"]


def test_switch_source_carries_a_real_terminal_verdict():
    client = _client(VIEWER_IN_MEDIA_ENGINEERS)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-switch-1")
    assert row["outcome"]["state"] == "succeeded"


def test_a_watched_action_in_flight_never_carries_headline_meaning_next_step():
    # in-flight is acceptance-only — it must not smuggle a verdict-shaped
    # payload in through the failure fields.
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-deploy-1")
    assert row["outcome"] == {"state": "in_flight", "detail": "dispatched"}


def test_a_row_with_an_unrecoverable_outcome_renders_unknown_end_to_end():
    # codex R496-C P1-2, through the full pipeline: DEPLOY_BLANK_OUTCOME is
    # a fully well-formed fmt=2 line whose `outcome` value happens to be
    # blank. The row still renders (gated normally, real actor/action/
    # target), and its outcome is an honest "unknown" — never a forged
    # "failed", never "in flight".
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-deploy-corrupted")
    assert row["actor"] == "erin"
    assert row["target"] == "wl-c"
    assert row["outcome"]["state"] == "unknown"
    assert row["outcome"]["detail"] == ""
    # The headline is what's most likely to be read alone — it must not
    # assert a verdict either way (the meaning is free to name "failed" as
    # one of several honest possibilities; that's accurate, not the bug).
    assert row["outcome"]["headline"] == "Outcome unknown"


# ----------------------------------------------------------------------
# AC 7 — an outage renders differently from an empty history.
# ----------------------------------------------------------------------

def test_loki_unreachable_is_a_distinct_reason_from_a_genuine_empty_history(monkeypatch):
    def _boom(**kwargs):
        raise audit_events.loki.LokiAPIError(0, "connection refused")

    monkeypatch.setattr(audit_events.loki, "query_range", _boom)
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["reason"] == "loki-unreachable"
    assert payload["events"] == []


def test_a_genuinely_empty_history_reads_ok_not_unreachable(monkeypatch):
    monkeypatch.setattr(audit_events.loki, "query_range", lambda **kwargs: [])
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["reason"] == ""
    assert payload["events"] == []


def test_loki_unconfigured_is_its_own_reason_and_makes_no_loki_call(monkeypatch):
    def _fail(**kwargs):
        raise AssertionError("must not call Loki when unconfigured")

    monkeypatch.setattr(audit_events.loki, "query_range", _fail)
    monkeypatch.setattr(audit_events.loki, "raw_runtime_config", _fail)
    client = _client(OPERATOR_ONLY, loki_configured=False)
    payload = client.get("/api/audit/events").json()
    assert payload["reason"] == "loki-unconfigured"
    assert payload["events"] == []


def test_unauthenticated_request_is_401_and_never_calls_loki(monkeypatch):
    def _fail(**kwargs):
        raise AssertionError("must not call Loki for an unauthenticated request")

    monkeypatch.setattr(audit_events.loki, "query_range", _fail)
    settings = Settings(runtime_mode="local", dev_login_enabled=True, loki=LokiSettings(url="http://loki.test"))
    client = TestClient(create_app(settings=settings))
    # deliberately no /auth/login — no session established
    resp = client.get("/api/audit/events")
    assert resp.status_code == 401


# ----------------------------------------------------------------------
# Window (conditions 1/2/3): known when derivable, unknown otherwise, never
# a hardcoded fallback.
# ----------------------------------------------------------------------

def test_window_known_from_the_global_when_no_stream_selector_matches():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["window"]["known"] is True
    assert payload["window"]["seconds"] == 168 * 3600


def test_window_uses_a_matching_stream_selector_over_the_global(monkeypatch):
    monkeypatch.setattr(
        audit_events.loki, "raw_runtime_config",
        lambda **kwargs: (
            "compactor:\n  retention_enabled: true\n"
            "limits_config:\n  retention_period: 168h\n  retention_stream:\n"
            '    - selector: \'{job="dmf-cms/dmf-cms"}\'\n      period: 720h\n      priority: 1\n'
        ),
    )
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["window"]["seconds"] == 720 * 3600


def test_window_unknown_when_retention_not_enforced(monkeypatch):
    monkeypatch.setattr(
        audit_events.loki, "raw_runtime_config",
        lambda **kwargs: "compactor:\n  retention_enabled: false\nlimits_config:\n  retention_period: 168h\n",
    )
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["window"]["known"] is False
    assert payload["window"]["seconds"] is None
    # window unavailability doesn't blank the lane -- events are still real
    assert payload["reason"] == ""


def test_window_unknown_when_config_endpoint_unavailable(monkeypatch):
    def _boom(**kwargs):
        raise audit_events.loki.LokiAPIError(404, "not found")

    monkeypatch.setattr(audit_events.loki, "raw_runtime_config", _boom)
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["window"]["known"] is False
    assert payload["reason"] == ""  # query_range still succeeded independently


# ----------------------------------------------------------------------
# F6 — a bound that binds must be disclosed.
# ----------------------------------------------------------------------

def test_not_capped_when_window_is_known_and_results_are_well_under_the_limit():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["window"]["known"] is True
    assert payload["capped"] is False


def test_capped_when_the_window_could_not_be_derived(monkeypatch):
    # No derived retention window means the query actually ran against the
    # technical ceiling, not a real bound — the response must say so rather
    # than reading as an ordinary, complete history.
    monkeypatch.setattr(
        audit_events.loki, "raw_runtime_config",
        lambda **kwargs: "compactor:\n  retention_enabled: false\nlimits_config:\n  retention_period: 168h\n",
    )
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["window"]["known"] is False
    assert payload["capped"] is True


def test_capped_when_the_result_count_hits_the_technical_limit(monkeypatch):
    # A saturated result count means Loki's own limit may have truncated
    # real rows before this function ever saw them.
    padded = FIXTURE_LINES + [DEPLOY] * (audit_events._MAX_RESULT_LINES - len(FIXTURE_LINES))

    def _saturated(*, url, selector, start_ns, end_ns, limit, timeout=10):
        return [{"stream": {}, "values": [[str(i), line] for i, line in enumerate(padded)]}]

    monkeypatch.setattr(audit_events.loki, "query_range", _saturated)
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert len(padded) == audit_events._MAX_RESULT_LINES
    assert payload["capped"] is True


# ----------------------------------------------------------------------
# dmfdeploy/dmf-cms#140 — the writer fix (2026-09-03 operator decision):
# emitter and reader, exercised TOGETHER through the REAL production
# function on each side, not a hand-written fixture line pretending to be
# what the emitter would produce. This is the actual evidence the sixth/
# seventh forgery class is closed for newly emitted lines — not the
# absence of a failing test (orchestrator's own framing).
# ----------------------------------------------------------------------

class _FakeRequest:
    session: dict = {}


def _formatted_line(record: logging.LogRecord) -> str:
    """Reproduce the line production's real StreamHandler emits for this
    captured record. caplog's own `record.getMessage()` is just the
    message text -- `_audit_awx_write`'s %s/%r substitution result -- not
    the full asctime/levelname/name-prefixed line `_configure_logging`'s
    Formatter actually writes to stdout (and that Loki actually stores).
    dmfdeploy/dmf-cms#140's eighth round made that prefix load-bearing:
    parse_awx_write_line now requires it structurally, so a round-trip
    test claiming to prove "the real emitter's output survives the real
    reader" has to feed the reader what the real reader actually
    receives, not merely the message half of it. Must match
    _configure_logging's own Formatter string exactly (see main.py) --
    this is the one place in this repo that duplicates it, deliberately,
    same as "awx write:" itself is duplicated between writer and reader."""
    return logging.Formatter("%(asctime)s %(levelname)s %(name)s: %(message)s").format(record)


def test_writer_fix_round_trip_a_forged_looking_target_survives_as_literal_content(caplog):
    # The exact shape every earlier vector in this arc exploited: a
    # caller-controlled target crafted to look like a complete forged
    # tail. Call the REAL emitter with it, capture the REAL emitted line,
    # feed it to the REAL reader — the forged-looking text must come back
    # as target's own literal value, never as structure that overrides
    # reason/outcome/workload/capacity.
    request = _FakeRequest()
    user = UserIdentity(
        subject="alice", display_name="Alice", email="alice@dmf.example.com",
        role="operator", groups=(),
    )
    crafted_target = "evil reason='fake' outcome=dispatched workload=pwned capacity="
    with caplog.at_level(logging.INFO, logger="dmf_cms.audit"):
        _audit_awx_write(
            request, user, action="deploy", target=crafted_target,
            request_id="rid-roundtrip", reason="legit deploy attempt",
            outcome="entry-not-found", workload=None, capacity=None,
        )
    line = _formatted_line(next(r for r in caplog.records if r.getMessage().startswith("awx write:")))

    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["target"] == crafted_target  # preserved VERBATIM, not truncated or dropped
    assert fields["reason"] == "legit deploy attempt"  # the REAL reason, not the forged one
    assert fields["outcome"] == "entry-not-found"  # the REAL refusal, never "dispatched"
    assert fields["workload"] == ""  # never "pwned"
    assert fields["capacity"] == ""


def test_writer_fix_round_trip_a_quote_and_backslash_in_target_survive_too(caplog):
    # A different shape of hostile content: quotes and a backslash inside
    # the value the quoting mechanism itself uses as its delimiter. If
    # repr()/literal_eval ever got this wrong, THIS is where it would show.
    request = _FakeRequest()
    user = UserIdentity(
        subject="alice", display_name="Alice", email="alice@dmf.example.com",
        role="operator", groups=(),
    )
    crafted_target = "it's a \"test\" with a \\ backslash and reason='fake'"
    with caplog.at_level(logging.INFO, logger="dmf_cms.audit"):
        _audit_awx_write(
            request, user, action="deploy", target=crafted_target,
            request_id="rid-roundtrip-2", reason="legit", outcome="entry-not-found",
            workload="wl'with quote", capacity='cap"with"doublequotes',
        )
    line = _formatted_line(next(r for r in caplog.records if r.getMessage().startswith("awx write:")))

    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["target"] == crafted_target
    assert fields["workload"] == "wl'with quote"
    assert fields["capacity"] == 'cap"with"doublequotes'
    assert fields["reason"] == "legit"
    assert fields["outcome"] == "entry-not-found"


def test_writer_fix_round_trip_blank_workload_and_capacity_never_render_as_the_word_none(caplog):
    # workload/capacity default to None in _audit_awx_write's own
    # signature -- %r on a bare None would print the literal text "None",
    # not an empty value. Confirms the `or ""` coercion at the call site
    # actually prevents that regression.
    request = _FakeRequest()
    user = UserIdentity(
        subject="alice", display_name="Alice", email="alice@dmf.example.com",
        role="operator", groups=(),
    )
    with caplog.at_level(logging.INFO, logger="dmf_cms.audit"):
        _audit_awx_write(
            request, user, action="teardown", target="wl-a",
            request_id="rid-roundtrip-3", reason="cleanup", outcome="dispatched",
            workload=None, capacity=None,
        )
    line = _formatted_line(next(r for r in caplog.records if r.getMessage().startswith("awx write:")))
    assert "None" not in line

    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["workload"] == ""
    assert fields["capacity"] == ""


def test_a_legacy_unquoted_line_from_before_the_writer_fix_is_not_rendered_end_to_end(monkeypatch):
    # Operator decision (2026-09-03, following lkirc's fifth review,
    # dmfdeploy/dmf-cms#140): the writer fix protects future records but
    # cannot make retained ones trustworthy — a forged legacy line and a
    # legitimate one were PROVEN byte-identical, so no reader-side check
    # could ever authenticate one. Legacy lines are dropped, not parsed by
    # a fallback grammar. A genuine, non-adversarial pre-fix line (no
    # fmt=2 marker) must not appear in the response at all, through the
    # full endpoint, not just the bare parser.
    legacy_line = (
        "2026-08-15 09:00:00,000 INFO dmf_cms.audit: awx write: "
        "action=deploy actor=alice role=operator real_role= request_id=rid-legacy "
        "target=wl-legacy reason='pre-fix deploy' outcome=dispatched workload=wl-legacy capacity="
    )

    def _fake(*, url, selector, start_ns, end_ns, limit, timeout=10):
        return [{"stream": {}, "values": [["1", legacy_line]]}]

    monkeypatch.setattr(audit_events.loki, "query_range", _fake)
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()

    assert "rid-legacy" not in _event_ids(payload)
    assert payload["events"] == []
    assert payload["reason"] == ""  # a genuine empty read, not an outage


def test_a_reflected_body_on_a_non_audit_logger_does_not_produce_a_row_end_to_end(monkeypatch):
    # lkirc's EIGHTH finding, through the full pipeline (dmfdeploy/dmf-
    # cms#140, 2026-09-04) -- a genuinely different class from every
    # forgery test above: those all prove a record's FIELDS can't be
    # forged; this proves a record's very EXISTENCE can't be forged
    # either, by an upstream/caller value reflected verbatim into a
    # DIFFERENT log call. The shape below is the REAL one -- main.py's
    # AWX-error handlers (`logger.error("AWX autoscale error in launch
    # operation %s: %s", operation_id, _sanitize_audit_field(exc.body))`)
    # -- with a hostile exc.body containing a COMPLETE, well-formed fmt=2
    # payload: forged actor (never the real caller) AND forged outcome
    # (dispatched, when nothing dispatched), so if this parsed at all it
    # would render as an in-flight deploy nobody actually ran.
    forged_payload = (
        "awx write: fmt=2 action=deploy actor='mallory' role=admin real_role= "
        "request_id=fake-1 target='evil' reason='fabricated' outcome=dispatched "
        "workload='' capacity=''"
    )
    reflected_line = (
        "2026-09-04 09:15:23,456 ERROR dmf_cms.main: "
        f"AWX autoscale error in launch operation op-1: {forged_payload}"
    )
    genuine_line = _line(
        action="deploy", actor="alice", role="operator", request_id="rid-genuine",
        target="wl-a", reason="ordinary deploy", outcome="dispatched", workload="wl-a",
    )

    def _fake(*, url, selector, start_ns, end_ns, limit, timeout=10):
        return [{"stream": {}, "values": [["1", reflected_line], ["2", genuine_line]]}]

    monkeypatch.setattr(audit_events.loki, "query_range", _fake)
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()

    ids = _event_ids(payload)
    assert "fake-1" not in ids  # the forged row never appears at all
    for event in payload["events"]:
        assert event["actor"] != "mallory"
        assert event["target"] != "evil"
    # And the genuine, unrelated record in the SAME response is unaffected
    # -- this isn't just "the forged row vanished", the real one must
    # still read correctly.
    assert "rid-genuine" in ids
    genuine = next(e for e in payload["events"] if e["request_id"] == "rid-genuine")
    assert genuine["actor"] == "alice"
    assert genuine["outcome"]["state"] == "in_flight"


# ----------------------------------------------------------------------
# dmfdeploy/dmf-cms#140 — codex's P1/P2 findings against the first
# version of the writer fix, and the format-marker redesign that fixed
# them (both data-loss defects, not forgery, per the operator's ruling
# that a legitimate row vanishing is squarely in scope). Round-tripped
# through the REAL emitter, same discipline as every other test in this
# section — the actual evidence, not the absence of a failing test.
# ----------------------------------------------------------------------

def test_writer_fix_p1_round_trip_workload_legitimately_containing_reason_marker_text(caplog):
    request = _FakeRequest()
    user = UserIdentity(
        subject="alice", display_name="Alice", email="alice@dmf.example.com",
        role="operator", groups=(),
    )
    with caplog.at_level(logging.INFO, logger="dmf_cms.audit"):
        _audit_awx_write(
            request, user, action="deploy", target="wl-a",
            request_id="rid-p1", reason="legit", outcome="dispatched",
            workload="reason='operator typo'", capacity=None,
        )
    line = _formatted_line(next(r for r in caplog.records if r.getMessage().startswith("awx write:")))

    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["workload"] == "reason='operator typo'"
    assert fields["reason"] == "legit"
    assert fields["outcome"] == "dispatched"


def test_writer_fix_p1_round_trip_capacity_legitimately_containing_reason_marker_text(caplog):
    request = _FakeRequest()
    user = UserIdentity(
        subject="alice", display_name="Alice", email="alice@dmf.example.com",
        role="operator", groups=(),
    )
    with caplog.at_level(logging.INFO, logger="dmf_cms.audit"):
        _audit_awx_write(
            request, user, action="deploy", target="wl-a",
            request_id="rid-p1b", reason="legit", outcome="dispatched",
            workload=None, capacity="reason='operator typo'",
        )
    line = _formatted_line(next(r for r in caplog.records if r.getMessage().startswith("awx write:")))

    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["capacity"] == "reason='operator typo'"
    assert fields["reason"] == "legit"


def test_writer_fix_round_trip_an_actor_forging_classification_fields_survives_as_literal_content(caplog):
    # actor is quoted as of this round specifically because it sits
    # BEFORE target in the classification scan -- through the REAL
    # emitter, a hostile subject claim must come back as target's own
    # literal actor value, never as forged role/real_role/request_id/
    # target structure.
    request = _FakeRequest()
    hostile_user = UserIdentity(
        subject="alice role=admin real_role= request_id=FAKE target='evil'",
        display_name="Alice", email="alice@dmf.example.com",
        role="operator", groups=(),
    )
    with caplog.at_level(logging.INFO, logger="dmf_cms.audit"):
        _audit_awx_write(
            request, hostile_user, action="deploy", target="wl-real",
            request_id="rid-actor", reason="legit", outcome="dispatched",
            workload=None, capacity=None,
        )
    line = _formatted_line(next(r for r in caplog.records if r.getMessage().startswith("awx write:")))

    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["actor"] == "alice role=admin real_role= request_id=FAKE target='evil'"
    assert fields["role"] == "operator"
    assert fields["real_role"] == ""
    assert fields["request_id"] == "rid-actor"
    assert fields["target"] == "wl-real"


def test_writer_fix_round_trip_every_quotable_field_survives_every_other_fields_marker_text(caplog):
    # THE PROPERTY, both halves, systematically: a caller-controlled
    # value containing marker-shaped text for ANY other field is
    # recorded faithfully AND cannot alter the parse of any other field.
    # Sweeps all five quotable fields (target/actor/reason/workload/
    # capacity), each forged with the OTHER four fields' marker text at
    # once, through the real emitter.
    hostile_text = "x target='t' actor='a' reason='r' outcome=dispatched workload='w' capacity='c' linked_request_id='l'"
    request = _FakeRequest()

    for field in ("target", "actor", "reason", "workload", "capacity"):
        kwargs = {
            "action": "deploy", "target": "wl-a", "request_id": f"rid-sweep-{field}",
            "reason": "legit", "outcome": "dispatched", "workload": None, "capacity": None,
        }
        if field == "actor":
            user = UserIdentity(
                subject=hostile_text, display_name="x", email="x@y.com", role="operator", groups=(),
            )
        else:
            user = UserIdentity(
                subject="alice", display_name="Alice", email="alice@dmf.example.com",
                role="operator", groups=(),
            )
            kwargs[field] = hostile_text

        caplog.clear()
        with caplog.at_level(logging.INFO, logger="dmf_cms.audit"):
            _audit_awx_write(request, user, **kwargs)
        line = _formatted_line(next(r for r in caplog.records if r.getMessage().startswith("awx write:")))

        fields = audit_events.parse_awx_write_line(line)
        assert fields is not None, f"field={field} dropped a row it should have preserved"
        assert fields[field] == hostile_text, f"field={field} was not preserved verbatim"
        # And the REST of the row is exactly what was actually sent, never
        # anything the hostile text's own embedded markers claimed.
        if field != "action":
            assert fields["action"] == "deploy"
        if field != "outcome":
            assert fields["outcome"] == "dispatched"
        if field != "target":
            assert fields["target"] == "wl-a"
        if field != "reason":
            assert fields["reason"] == "legit"
