"""Unit tests for the pure functions behind dmfdeploy/dmfdeploy#496's
Activity History lane — line parsing, retention-window derivation, class
membership/gating, and outcome/disclosure mapping. No FastAPI, no Loki I/O:
every fixture here is a literal string, never generated by calling the code
under test (plan §7 AC 5a's tautology ban applies to these building blocks
too, not just the endpoint-level fixture).
"""

from __future__ import annotations

import dmf_cms.audit_events as audit_events


# ----------------------------------------------------------------------
# parse_awx_write_line
# ----------------------------------------------------------------------

def test_parses_a_plain_line_with_logging_prefix():
    line = (
        "2026-09-03 12:00:00,000 INFO dmf_cms.audit: awx write: "
        "action=deploy actor=alice role=operator real_role= request_id=rid-1 "
        "target=wl-a reason='demo deploy' outcome=dispatched workload=wl-a capacity="
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields == {
        "action": "deploy",
        "actor": "alice",
        "role": "operator",
        "real_role": "",
        "request_id": "rid-1",
        "target": "wl-a",
        "reason": "demo deploy",
        "outcome": "dispatched",
        "workload": "wl-a",
        "capacity": "",
        "linked_request_id": "",
    }


def test_parses_the_auto_rollback_trailing_field():
    line = (
        "INFO dmf_cms: awx write: action=rollback actor=system:auto-rollback role=system "
        "real_role= request_id=rid-child target=run-123 reason='auto: deploy wl-a failed' "
        "outcome=auto-triggered workload= capacity= linked_request_id=rid-parent"
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields["linked_request_id"] == "rid-parent"
    assert fields["target"] == "run-123"
    assert fields["workload"] == ""


def test_reason_containing_the_next_markers_own_text_does_not_corrupt_parsing():
    # The trap named in the plan §4.1/§4.2: reason is a Python repr and may
    # legitimately contain " outcome=" as ordinary text. A parser that
    # anchors on the NEXT bare marker instead of quote-scanning reason
    # would truncate it here.
    line = (
        "awx write: action=teardown actor=alice role=operator real_role= "
        "request_id=rid-2 target=wl-b reason='fixing outcome=broken thing, ok?' "
        "outcome=dispatched workload= capacity="
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields["reason"] == "fixing outcome=broken thing, ok?"
    assert fields["outcome"] == "dispatched"


def test_reason_with_escaped_quote_round_trips():
    line = (
        r"awx write: action=deploy actor=alice role=operator real_role= "
        r"request_id=rid-3 target=wl-a reason='it\'s fine' "
        "outcome=dispatched workload= capacity="
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields["reason"] == "it's fine"


def test_missing_awx_write_prefix_returns_none():
    assert audit_events.parse_awx_write_line("some unrelated log line") is None


def test_missing_field_returns_none():
    line = "awx write: action=deploy actor=alice role=operator real_role= request_id=rid-1"
    assert audit_events.parse_awx_write_line(line) is None


def test_unterminated_reason_quote_retains_the_row_with_safe_blank_fields():
    # codex R496-A F5: a malformed `reason` is an ENRICHMENT failure, not a
    # CLASSIFICATION failure (AC 5b) — action/actor/request_id/target all
    # parsed cleanly here (from a region reason's own content can never
    # reach), so dropping the whole row over one damaged field would
    # discard an otherwise-usable record. Retained with reason="".
    #
    # codex R496-A NEW-2: everything AFTER the broken reason is also blank,
    # never recovered by scanning forward — see
    # test_forgery_resistance_* below for why. This line's trailing text
    # (which LOOKS like outcome=dispatched) must NOT end up as the row's
    # outcome.
    line = (
        "awx write: action=deploy actor=alice role=operator real_role= "
        "request_id=rid-1 target=wl-a reason='never closes outcome=dispatched workload= capacity="
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["action"] == "deploy"
    assert fields["request_id"] == "rid-1"
    assert fields["reason"] == ""
    assert fields["outcome"] == ""
    assert fields["workload"] == ""


def test_reason_and_everything_before_it_missing_still_fails_to_parse():
    # A DIFFERENT failure: `reason=` itself is never found at all (not just
    # unterminated) — there is nothing to anchor even the classification
    # fields against reason's start, so the row is dropped.
    line = "awx write: action=deploy actor=alice role=operator real_role= request_id=rid-1 target=wl-a"
    assert audit_events.parse_awx_write_line(line) is None


def test_forgery_resistance_a_malformed_reason_cannot_forge_outcome_or_workload():
    # codex R496-A NEW-2, the property this test is named for: reason is
    # C5's MANDATORY, OPERATOR-CONTROLLED field — main.py's _require_reason
    # extracts it verbatim from the request body, then logs it via `reason=
    # %r`. A row must never let text WITHIN a broken reason be picked up as
    # later fields; that would let an operator author their own
    # outcome/workload for an audit record purely through what they type as
    # their reason. This line's reason is deliberately unterminated and its
    # own text contains a full set of fake trailing fields.
    line = (
        "awx write: action=deploy actor=alice role=operator real_role= "
        "request_id=rid-real target=wl-a "
        "reason='malicious outcome=dispatched workload=stolen-workload capacity= linked_request_id=evil-parent"
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["action"] == "deploy"
    assert fields["actor"] == "alice"  # genuine, parsed strictly BEFORE reason — never forgeable
    assert fields["request_id"] == "rid-real"
    assert fields["reason"] == ""
    # Nothing after the broken reason is ever trusted — all fail-safe
    # empty, never the attacker-authored values embedded in reason's text.
    assert fields["outcome"] == ""
    assert fields["workload"] == ""
    assert fields["linked_request_id"] == ""
    # codex R496-C P1-2: a fail-safe empty outcome renders as UNKNOWN, not
    # a forged success/in-flight claim — and, just as importantly, not a
    # forged FAILURE either. "Not proven in flight" is not "the action
    # failed"; that would be this lane claiming knowledge it lost, the
    # same defect this round exists to remove with the sign flipped.
    assert audit_events.resolve_outcome_state("deploy", fields["outcome"]) == "unknown"


def test_forgery_resistance_cannot_attribute_the_row_to_a_different_actor():
    # A more targeted attempt: the injected text tries to name a DIFFERENT
    # actor than the real one, which is what an audit record's whole
    # purpose depends on getting right. Since actor is parsed strictly
    # BEFORE reason and never re-derived from anything after it, this must
    # have zero effect.
    line = (
        "awx write: action=deploy actor=alice role=operator real_role= "
        "request_id=rid-real target=wl-a "
        "reason='forged actor=mallory role=admin outcome=dispatched"
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["actor"] == "alice"
    assert fields["role"] == "operator"
    assert fields["outcome"] == ""


# ----------------------------------------------------------------------
# dmf-cms#140 (lkirc, BLOCKING; extended by the orchestrator's own sweep):
# "no caller-influenced field's value may alter the parse of any other
# field." Every field except `reason` is %s-formatted (control-character
# escaped only, no `=`/space escaping) -- reason's own scan is quote-aware
# and safe on its content BY CONSTRUCTION (see the tests above); these are
# the fields that are NOT. One test per field, named for the property each
# one proves, plus the two boundary regressions this fix must never
# reintroduce.
#
# THE ASSERTION SHAPE MATTERS (orchestrator's own correction, mid-round):
# "returns None" alone can pass for an incidental reason unrelated to
# whether the injection actually failed to move a boundary -- e.g. some
# OTHER field's marker happening to duplicate for an unrelated reason on
# that specific crafted line. Every test below instead asserts the
# PROPERTY directly against the SPECIFIC value the attacker chose for the
# SPECIFIC field they were trying to forge: either the row was dropped, or
# that exact field never holds that exact attacker-chosen value. A
# same-shaped CONTROL case (no injection) is included once to pin what a
# clean parse of equivalent data actually produces, so the two together
# show the injection changed nothing it shouldn't have.
# ----------------------------------------------------------------------

def test_property_a_forged_target_cannot_alter_the_parse_of_later_fields():
    # The exact shape reported: an unknown catalog key (target, caller-
    # supplied via the deploy path parameter, reaches the audit line with
    # NO prior validation on the entry-not-found refusal path) crafted to
    # embed a fake reason/outcome/workload, hijacking the boundary so a
    # REFUSED deploy would otherwise read as an in-flight one.
    crafted_target = "evil-target reason='fake' outcome=dispatched workload=pwned capacity="
    line = (
        f"awx write: action=deploy actor=alice role=operator real_role= "
        f"request_id=rid-real target={crafted_target} reason='legit deploy attempt' "
        f"outcome=entry-not-found workload= capacity="
    )
    fields = audit_events.parse_awx_write_line(line)
    if fields is not None:
        assert fields["outcome"] != "dispatched"
        assert fields["workload"] != "pwned"
        assert fields["target"] != "evil-target"  # the crafted prefix must not survive either


def test_property_a_forged_workload_cannot_alter_the_parse_of_later_fields():
    # workload is EQUALLY caller-influenced (main.py:384,
    # `body.get("workload")`, no validation) and sits structurally before
    # capacity/linked_request_id -- the same injection shape, one field
    # later in the schema.
    crafted_workload = "pwned capacity=FAKE linked_request_id=stolen-parent"
    line = (
        f"awx write: action=rollback actor=system:auto-rollback role=system real_role= "
        f"request_id=rid-real target=run-123 reason='auto rollback' "
        f"outcome=facility-busy workload={crafted_workload} "
        f"capacity= linked_request_id=rid-genuine-parent"
    )
    fields = audit_events.parse_awx_write_line(line)
    if fields is not None:
        assert fields["capacity"] != "FAKE"
        assert fields["linked_request_id"] != "stolen-parent"


def test_property_a_forged_actor_cannot_alter_the_parse_of_later_fields():
    # actor is user.subject -- OIDC's `sub` claim, IdP-controlled and not
    # directly caller-influenced in this system's actual configuration
    # (reasoned about, not assumed, per the review that asked for this).
    # Tested anyway: the fix is a structural, field-agnostic property, not
    # an allowlist of "the fields we proved exploitable today" -- it must
    # hold even if a future IdP/claim-mapping change ever loosened
    # `actor`'s trust boundary.
    crafted_actor = "alice role=admin real_role= request_id=rid-forged target=stolen-target reason='fake' outcome=dispatched workload=pwned capacity="
    line = (
        f"awx write: action=deploy actor={crafted_actor} role=operator real_role= "
        f"request_id=rid-real target=wl-a reason='legit' "
        f"outcome=facility-busy workload= capacity="
    )
    fields = audit_events.parse_awx_write_line(line)
    if fields is not None:
        assert fields["role"] != "admin"
        assert fields["request_id"] != "rid-forged"
        assert fields["target"] != "stolen-target"
        assert fields["outcome"] != "dispatched"
        assert fields["workload"] != "pwned"


def test_property_a_forged_capacity_cannot_forge_linked_request_id():
    # The orchestrator's own follow-up sweep, not in lkirc's report:
    # `linked_request_id` is the one marker that's LEGITIMATELY absent on
    # most lines (0-or-1, unlike every other marker's always-exactly-1),
    # so a single injected occurrence in capacity's own (otherwise
    # unbounded) value has no duplicate to be caught by. `capacity` is
    # server-computed today (_capacity_audit_summary, never caller text)
    # -- fixed anyway, since "not caller-controlled today" is the exact
    # reasoning this round exists to stop trusting. Auto-rollback is the
    # ONLY class linked_request_id means anything for, and its own
    # emission hardcodes workload/capacity blank (main.py's direct
    # module-logger calls take no %s for either) -- so this line's
    # action=deploy makes the forged value provably a forgery, not a
    # coincidence.
    line = (
        "awx write: action=deploy actor=alice role=operator real_role= "
        "request_id=rid-real target=wl-a reason='legit' "
        "outcome=dispatched workload=wl-a capacity=c linked_request_id=FORGEDPARENT"
    )
    fields = audit_events.parse_awx_write_line(line)
    if fields is not None:
        assert fields["linked_request_id"] != "FORGEDPARENT"


def test_property_a_genuine_auto_rollback_linked_request_id_still_parses():
    # Control case for the test above: the SAME trailing field, on the
    # class it's actually legitimate for, with nothing injected, must
    # still parse normally -- the fix must not blanket-reject every
    # linked_request_id, only ones inconsistent with their own row's
    # action/actor.
    line = (
        "awx write: action=rollback actor=system:auto-rollback role=system real_role= "
        "request_id=rid-child target=run-123 reason='auto: deploy wl-a failed' "
        "outcome=auto-triggered workload= capacity= linked_request_id=rid-parent"
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["linked_request_id"] == "rid-parent"


def test_property_a_legitimate_reason_mentioning_marker_like_text_still_parses():
    # Regression guard: the fix must not reject an HONEST reason that
    # happens to mention marker-shaped text in ordinary prose (e.g. "role="
    # as a genuine word an operator typed) -- only text OUTSIDE reason's
    # own, already-safely-quote-scanned span is checked for duplicates.
    line = (
        "awx write: action=deploy actor=alice role=operator real_role= "
        "request_id=rid-1 target=wl-a "
        "reason='confirmed with role=lead engineer, target=wl-a is correct' "
        "outcome=dispatched workload=wl-a capacity="
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["reason"] == "confirmed with role=lead engineer, target=wl-a is correct"
    assert fields["outcome"] == "dispatched"


def test_property_a_genuinely_truncated_reason_still_uses_the_safe_fallback():
    # Regression guard: a reason that fails to quote-scan at all (Case B,
    # the round-2 NEW-2 fix) must still take the existing safe-blank
    # fallback -- it never reaches this fix's duplicate check, because
    # nothing past a broken reason is trusted anyway (see that branch's
    # own comment for why it's already immune).
    line = (
        "awx write: action=deploy actor=alice role=operator real_role= "
        "request_id=rid-1 target=wl-a reason='never closes outcome=dispatched workload= capacity="
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["reason"] == ""
    assert fields["outcome"] == ""


# ----------------------------------------------------------------------
# resolve_retention_window
# ----------------------------------------------------------------------

_LABELS = {"namespace": "dmf-cms", "job": "dmf-cms/dmf-cms"}


def test_retention_not_enforced_when_compactor_disabled():
    config = """
compactor:
  retention_enabled: false
limits_config:
  retention_period: 168h
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.known is False
    assert window.reason == "not-enforced"


def test_retention_falls_back_to_global_when_no_stream_selector_matches():
    # This is condition 1's exact case: the queried job label matches
    # neither the k3s-audit nor the security-job stream rule, so today the
    # global is correct -- but the code must evaluate that, not assume it.
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
  retention_stream:
    - selector: '{job="k3s-audit"}'
      period: 720h
      priority: 2
    - selector: '{job=~".+-security"}'
      period: 720h
      priority: 1
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.known is True
    assert window.seconds == 168 * 3600
    assert window.reason == ""


def test_retention_uses_matching_stream_selector_over_global():
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
  retention_stream:
    - selector: '{job="dmf-cms/dmf-cms"}'
      period: 720h
      priority: 1
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.known is True
    assert window.seconds == 720 * 3600


def test_retention_stream_priority_breaks_a_tie_between_two_matching_rules():
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
  retention_stream:
    - selector: '{job=~"dmf-cms.*"}'
      period: 240h
      priority: 1
    - selector: '{job="dmf-cms/dmf-cms"}'
      period: 480h
      priority: 5
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.seconds == 480 * 3600


def test_retention_equal_priority_tie_takes_the_shorter_period():
    # codex R496-A F2a: Loki resolves an equal-priority tie by taking the
    # SHORTER period, not whichever rule this code happened to encounter
    # first in the list. Rule order below is deliberately the OPPOSITE of
    # the expected answer (720h listed first) so a "first encountered"
    # bug would report the wrong, longer window.
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
  retention_stream:
    - selector: '{job="dmf-cms/dmf-cms"}'
      period: 720h
      priority: 3
    - selector: '{job=~"dmf-cms.*"}'
      period: 240h
      priority: 3
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.seconds == 240 * 3600


def test_retention_selector_missing_label_treated_as_empty_string():
    # codex R496-A F2b: Prometheus/Loki matcher semantics treat an absent
    # label as present-with-value-"" — so a negative matcher on a label the
    # query never carries legitimately MATCHES. _LABELS has no "container"
    # key at all; the old (buggy) behaviour treated a missing label as an
    # automatic non-match, silently falling through to the (longer) global.
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
  retention_stream:
    - selector: '{job="dmf-cms/dmf-cms", container!="foo"}'
      period: 24h
      priority: 1
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.seconds == 24 * 3600


def test_retention_selector_positive_missing_label_match_does_not_match():
    # Same semantics, opposite polarity: a POSITIVE matcher on an absent
    # label only matches an explicit empty string, never silently.
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
  retention_stream:
    - selector: '{job="dmf-cms/dmf-cms", container="foo"}'
      period: 24h
      priority: 1
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.seconds == 168 * 3600  # the stream rule never matched; falls to global


def test_retention_unavailable_on_unparseable_yaml():
    window = audit_events.resolve_retention_window("not: valid: yaml: [", _LABELS)
    assert window.known is False
    assert window.reason == "unparseable"


def test_retention_unparseable_on_garbage_duration():
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: not-a-duration
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.known is False
    assert window.reason == "unparseable"


def test_retention_unparseable_when_limits_config_missing():
    config = "compactor:\n  retention_enabled: true\n"
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.known is False
    assert window.reason == "unparseable"


def test_retention_a_broken_regex_selector_never_matches_and_never_crashes():
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
  retention_stream:
    - selector: '{job=~"("}'
      period: 720h
      priority: 9
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.known is True
    assert window.seconds == 168 * 3600  # falls back to global, does not crash


# ----------------------------------------------------------------------
# classify_record / user_passes_gate — the closed membership table
# ----------------------------------------------------------------------

def test_classify_covered_classes():
    assert audit_events.classify_record("deploy", "alice") == "deploy"
    assert audit_events.classify_record("teardown", "alice") == "teardown"
    assert audit_events.classify_record("switch-source", "bob") == "switch-source"


def test_classify_splits_rollback_by_actor():
    assert audit_events.classify_record("rollback", "system:auto-rollback") == "auto-rollback"
    assert audit_events.classify_record("rollback", "alice") == "rollback"


def test_classify_excluded_classes_are_named_not_dropped_from_the_table():
    for action in ("finalise-purge", "launch", "verify-drain"):
        cls = audit_events.classify_record(action, "alice")
        assert cls == action
        assert audit_events._CLASS_INFO[cls]["status"] != audit_events.COVERED


def test_classify_unrecognised_action_fails_closed():
    assert audit_events.classify_record("mystery-action", "alice") is None


def test_gate_operator_role_passes_operator_classes_not_media_workloads():
    assert audit_events.user_passes_gate("deploy", role="operator", groups=()) is True
    assert audit_events.user_passes_gate("teardown", role="operator", groups=()) is True
    assert audit_events.user_passes_gate("auto-rollback", role="operator", groups=()) is True
    assert audit_events.user_passes_gate("switch-source", role="operator", groups=()) is False


def test_gate_viewer_in_media_engineers_passes_only_switch_source():
    groups = ("dmf-console-viewer", "media-engineers")
    assert audit_events.user_passes_gate("switch-source", role="viewer", groups=groups) is True
    assert audit_events.user_passes_gate("deploy", role="viewer", groups=groups) is False


def test_gate_excluded_classes_pass_for_nobody():
    for cls in ("finalise-purge", "launch", "verify-drain", "rollback"):
        assert audit_events.user_passes_gate(cls, role="admin", groups=("media-engineers",)) is False


# ----------------------------------------------------------------------
# outcome / disclosure mapping
# ----------------------------------------------------------------------

def test_a_blank_outcome_is_unknown_not_failed_for_every_watched_action():
    # codex R496-C P1-2: the property this test is named for. A blank
    # outcome means the record's outcome field was lost (unrecoverable),
    # not that the action failed — rendering it as a definite failure
    # would be this lane claiming knowledge it does not have, the same
    # defect the whole round exists to remove, opposite sign. Covers
    # every action resolve_outcome_state actually branches on, including
    # switch-source (which has its own separate "== active" check that
    # must not see a blank outcome fall through to its else-failed arm).
    for action in ("deploy", "teardown", "rollback", "finalise-purge", "switch-source"):
        assert audit_events.resolve_outcome_state(action, "") == "unknown"


def test_a_blank_outcome_is_unknown_even_though_blank_is_never_a_real_refusal_token():
    # Distinguishes the new THIRD case from the unenumerated-refusal rule
    # (F3) it must never be folded into: a REAL, non-blank, never-seen
    # token still correctly renders failed (re-confirming F3 is
    # untouched), while blank specifically renders unknown — proving
    # "unknown" is not just another way of writing "unenumerated".
    assert audit_events.resolve_outcome_state("deploy", "some-token-nobody-catalogued") == "failed"
    assert audit_events.resolve_outcome_state("deploy", "") == "unknown"


def test_build_outcome_unknown_state_never_asserts_a_definite_verdict():
    result = audit_events.build_outcome("deploy", "")
    assert result["state"] == "unknown"
    # The headline is the one line most likely to be read alone — it must
    # not claim a verdict either way. The meaning is free to name "failed"
    # as one of several honest POSSIBILITIES (that's the accurate
    # statement); the bug this guards against is ASSERTING it as fact.
    assert result["headline"] == "Outcome unknown"
    assert result["meaning"] == (
        "This action's outcome could not be read from the record — "
        "it may have succeeded, failed, or still be in progress."
    )


def test_watched_action_acceptance_outcome_is_in_flight():
    for action, outcome in (("deploy", "dispatched"), ("teardown", "launched"), ("rollback", "auto-triggered")):
        result = audit_events.build_outcome(action, outcome)
        assert result == {"state": "in_flight", "detail": outcome}


def test_reattach_shaped_acceptance_outcomes_are_also_in_flight():
    # "reattached" (get_or_create found an existing op, no new dispatch) and
    # "already-active" (the sync flow's own idempotency guard found an
    # in-flight AWX job) are both genuine in-flight realities reached via a
    # different code path than a fresh dispatch — main.py:4769, :4874 (and
    # the teardown/rollback siblings).
    for action in ("deploy", "teardown"):
        for outcome in ("reattached", "already-active"):
            assert audit_events.build_outcome(action, outcome)["state"] == "in_flight"
    assert audit_events.build_outcome("rollback", "already-in-progress")["state"] == "in_flight"


def test_already_active_other_run_is_a_refusal_not_an_acceptance():
    # codex R496-A F3's concrete proof case: rollback's identity-mismatch
    # branch (main.py:5315) never dispatches THIS run's rollback — a
    # DIFFERENT run's job was found active, and the request is refused
    # (409). Textually similar to "already-active" but semantically its
    # opposite; must render failed.
    result = audit_events.build_outcome("rollback", "already-active-other-run")
    assert result["state"] == "failed"


def test_an_unenumerated_refusal_token_is_terminal_not_in_flight():
    # codex R496-A F3: the fix must be allowlist-shaped, not "add the
    # missing tokens to a denylist" — main.py emits far more refusal
    # tokens than any denylist could enumerate (confirmation-mismatch,
    # conflict-active-job, entry-not-found, invalid-run-id, ... the list
    # keeps growing). A token this test has never seen before must STILL
    # render failed for a watched action, proving the acceptance set is
    # closed rather than the refusal set.
    for action in ("deploy", "teardown", "rollback", "finalise-purge"):
        result = audit_events.build_outcome(action, "some-refusal-token-invented-for-this-test")
        assert result["state"] == "failed"


def test_switch_source_active_is_a_real_succeeded_verdict():
    result = audit_events.build_outcome("switch-source", "active")
    assert result == {"state": "succeeded", "detail": "active"}


def test_switch_source_non_active_is_failed_with_generic_default_copy():
    result = audit_events.build_outcome("switch-source", "failed_rollback_required")
    assert result["state"] == "failed"
    assert result["detail"] == "failed_rollback_required"  # raw preserved, expert-only
    assert "failed_rollback_required" not in result["headline"]
    assert "failed_rollback_required" not in result["meaning"]


def test_refusal_token_overrides_watched_acceptance_and_gets_plain_language_copy():
    result = audit_events.build_outcome("deploy", "facility-busy")
    assert result["state"] == "failed"
    assert result["headline"] == "Another operation is already using this facility"
    assert result["detail"] == "facility-busy"  # raw string carried, never in headline/meaning/next_step
    for key in ("headline", "meaning", "next_step"):
        assert "facility-busy" not in result[key]


def test_awx_error_prefix_gets_generic_copy_and_keeps_raw_as_detail_only():
    result = audit_events.build_outcome("teardown", "awx-error:503")
    assert result["state"] == "failed"
    assert result["detail"] == "awx-error:503"
    for key in ("headline", "meaning", "next_step"):
        assert "awx-error:503" not in result[key]


def test_unrecognised_refusal_token_still_gets_honest_generic_copy_never_raw():
    # _describe_failure directly: the plan's refusal vocabulary (§4.4) is a
    # closed set, same principle as the class table — a token outside it
    # must still never leak raw at default, even with no specific copy
    # authored for it yet.
    copy = audit_events._describe_failure("some-new-refusal-nobody-mapped-yet")
    for key in ("headline", "meaning", "next_step"):
        assert "some-new-refusal-nobody-mapped-yet" not in copy[key]


def test_resolve_outcome_state_fails_safe_outside_the_known_vocabulary():
    # Defensive only: build_outcome is never called on an excluded row in
    # the real pipeline (list_audit_events drops those before reaching it),
    # but the function itself must not invent an in-flight/succeeded claim
    # for an action it does not recognise.
    assert audit_events.resolve_outcome_state("some-unknown-action", "whatever") == "failed"
