"""Unit tests for the pure functions behind dmfdeploy/dmfdeploy#496's
Activity History lane — line parsing, retention-window derivation, class
membership/gating, and outcome/disclosure mapping. No FastAPI, no Loki I/O:
every fixture here is a literal string, never generated by calling the code
under test (plan §7 AC 5a's tautology ban applies to these building blocks
too, not just the endpoint-level fixture).
"""

from __future__ import annotations

import dmf_cms.audit_events as audit_events


# ----------------------------------------------------------------------
# parse_awx_write_line
# ----------------------------------------------------------------------

def test_parses_a_plain_line_with_logging_prefix():
    line = (
        "2026-09-03 12:00:00,000 INFO dmf_cms.audit: awx write: "
        "action=deploy actor=alice role=operator real_role= request_id=rid-1 "
        "target=wl-a reason='demo deploy' outcome=dispatched workload=wl-a capacity="
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields == {
        "action": "deploy",
        "actor": "alice",
        "role": "operator",
        "real_role": "",
        "request_id": "rid-1",
        "target": "wl-a",
        "reason": "demo deploy",
        "outcome": "dispatched",
        "workload": "wl-a",
        "capacity": "",
        "linked_request_id": "",
    }


def test_parses_the_auto_rollback_trailing_field():
    line = (
        "INFO dmf_cms: awx write: action=rollback actor=system:auto-rollback role=system "
        "real_role= request_id=rid-child target=run-123 reason='auto: deploy wl-a failed' "
        "outcome=auto-triggered workload= capacity= linked_request_id=rid-parent"
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields["linked_request_id"] == "rid-parent"
    assert fields["target"] == "run-123"
    assert fields["workload"] == ""


def test_reason_containing_the_next_markers_own_text_does_not_corrupt_parsing():
    # The trap named in the plan §4.1/§4.2: reason is a Python repr and may
    # legitimately contain " outcome=" as ordinary text. A parser that
    # anchors on the NEXT bare marker instead of quote-scanning reason
    # would truncate it here.
    line = (
        "awx write: action=teardown actor=alice role=operator real_role= "
        "request_id=rid-2 target=wl-b reason='fixing outcome=broken thing, ok?' "
        "outcome=dispatched workload= capacity="
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields["reason"] == "fixing outcome=broken thing, ok?"
    assert fields["outcome"] == "dispatched"


def test_reason_with_escaped_quote_round_trips():
    line = (
        r"awx write: action=deploy actor=alice role=operator real_role= "
        r"request_id=rid-3 target=wl-a reason='it\'s fine' "
        "outcome=dispatched workload= capacity="
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields["reason"] == "it's fine"


def test_missing_awx_write_prefix_returns_none():
    assert audit_events.parse_awx_write_line("some unrelated log line") is None


def test_missing_field_returns_none():
    line = "awx write: action=deploy actor=alice role=operator real_role= request_id=rid-1"
    assert audit_events.parse_awx_write_line(line) is None


def test_unterminated_reason_quote_returns_none():
    line = (
        "awx write: action=deploy actor=alice role=operator real_role= "
        "request_id=rid-1 target=wl-a reason='never closes outcome=dispatched workload= capacity="
    )
    assert audit_events.parse_awx_write_line(line) is None


# ----------------------------------------------------------------------
# resolve_retention_window
# ----------------------------------------------------------------------

_LABELS = {"namespace": "dmf-cms", "job": "dmf-cms/dmf-cms"}


def test_retention_not_enforced_when_compactor_disabled():
    config = """
compactor:
  retention_enabled: false
limits_config:
  retention_period: 168h
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.known is False
    assert window.reason == "not-enforced"


def test_retention_falls_back_to_global_when_no_stream_selector_matches():
    # This is condition 1's exact case: the queried job label matches
    # neither the k3s-audit nor the security-job stream rule, so today the
    # global is correct -- but the code must evaluate that, not assume it.
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
  retention_stream:
    - selector: '{job="k3s-audit"}'
      period: 720h
      priority: 2
    - selector: '{job=~".+-security"}'
      period: 720h
      priority: 1
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.known is True
    assert window.seconds == 168 * 3600
    assert window.reason == ""


def test_retention_uses_matching_stream_selector_over_global():
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
  retention_stream:
    - selector: '{job="dmf-cms/dmf-cms"}'
      period: 720h
      priority: 1
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.known is True
    assert window.seconds == 720 * 3600


def test_retention_stream_priority_breaks_a_tie_between_two_matching_rules():
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
  retention_stream:
    - selector: '{job=~"dmf-cms.*"}'
      period: 240h
      priority: 1
    - selector: '{job="dmf-cms/dmf-cms"}'
      period: 480h
      priority: 5
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.seconds == 480 * 3600


def test_retention_unavailable_on_unparseable_yaml():
    window = audit_events.resolve_retention_window("not: valid: yaml: [", _LABELS)
    assert window.known is False
    assert window.reason == "unparseable"


def test_retention_unparseable_on_garbage_duration():
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: not-a-duration
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.known is False
    assert window.reason == "unparseable"


def test_retention_unparseable_when_limits_config_missing():
    config = "compactor:\n  retention_enabled: true\n"
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.known is False
    assert window.reason == "unparseable"


def test_retention_a_broken_regex_selector_never_matches_and_never_crashes():
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
  retention_stream:
    - selector: '{job=~"("}'
      period: 720h
      priority: 9
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.known is True
    assert window.seconds == 168 * 3600  # falls back to global, does not crash


# ----------------------------------------------------------------------
# classify_record / user_passes_gate — the closed membership table
# ----------------------------------------------------------------------

def test_classify_covered_classes():
    assert audit_events.classify_record("deploy", "alice") == "deploy"
    assert audit_events.classify_record("teardown", "alice") == "teardown"
    assert audit_events.classify_record("switch-source", "bob") == "switch-source"


def test_classify_splits_rollback_by_actor():
    assert audit_events.classify_record("rollback", "system:auto-rollback") == "auto-rollback"
    assert audit_events.classify_record("rollback", "alice") == "rollback"


def test_classify_excluded_classes_are_named_not_dropped_from_the_table():
    for action in ("finalise-purge", "launch", "verify-drain"):
        cls = audit_events.classify_record(action, "alice")
        assert cls == action
        assert audit_events._CLASS_INFO[cls]["status"] != audit_events.COVERED


def test_classify_unrecognised_action_fails_closed():
    assert audit_events.classify_record("mystery-action", "alice") is None


def test_gate_operator_role_passes_operator_classes_not_media_workloads():
    assert audit_events.user_passes_gate("deploy", role="operator", groups=()) is True
    assert audit_events.user_passes_gate("teardown", role="operator", groups=()) is True
    assert audit_events.user_passes_gate("auto-rollback", role="operator", groups=()) is True
    assert audit_events.user_passes_gate("switch-source", role="operator", groups=()) is False


def test_gate_viewer_in_media_engineers_passes_only_switch_source():
    groups = ("dmf-console-viewer", "media-engineers")
    assert audit_events.user_passes_gate("switch-source", role="viewer", groups=groups) is True
    assert audit_events.user_passes_gate("deploy", role="viewer", groups=groups) is False


def test_gate_excluded_classes_pass_for_nobody():
    for cls in ("finalise-purge", "launch", "verify-drain", "rollback"):
        assert audit_events.user_passes_gate(cls, role="admin", groups=("media-engineers",)) is False


# ----------------------------------------------------------------------
# outcome / disclosure mapping
# ----------------------------------------------------------------------

def test_watched_action_acceptance_outcome_is_in_flight():
    for action, outcome in (("deploy", "dispatched"), ("teardown", "launched"), ("rollback", "auto-triggered")):
        result = audit_events.build_outcome(action, outcome)
        assert result == {"state": "in_flight", "detail": outcome}


def test_switch_source_active_is_a_real_succeeded_verdict():
    result = audit_events.build_outcome("switch-source", "active")
    assert result == {"state": "succeeded", "detail": "active"}


def test_switch_source_non_active_is_failed_with_generic_default_copy():
    result = audit_events.build_outcome("switch-source", "failed_rollback_required")
    assert result["state"] == "failed"
    assert result["detail"] == "failed_rollback_required"  # raw preserved, expert-only
    assert "failed_rollback_required" not in result["headline"]
    assert "failed_rollback_required" not in result["meaning"]


def test_refusal_token_overrides_watched_acceptance_and_gets_plain_language_copy():
    result = audit_events.build_outcome("deploy", "facility-busy")
    assert result["state"] == "failed"
    assert result["headline"] == "Another operation is already using this facility"
    assert result["detail"] == "facility-busy"  # raw string carried, never in headline/meaning/next_step
    for key in ("headline", "meaning", "next_step"):
        assert "facility-busy" not in result[key]


def test_awx_error_prefix_gets_generic_copy_and_keeps_raw_as_detail_only():
    result = audit_events.build_outcome("teardown", "awx-error:503")
    assert result["state"] == "failed"
    assert result["detail"] == "awx-error:503"
    for key in ("headline", "meaning", "next_step"):
        assert "awx-error:503" not in result[key]


def test_unrecognised_refusal_token_still_gets_honest_generic_copy_never_raw():
    # _describe_failure directly: the plan's refusal vocabulary (§4.4) is a
    # closed set, same principle as the class table — a token outside it
    # must still never leak raw at default, even with no specific copy
    # authored for it yet.
    copy = audit_events._describe_failure("some-new-refusal-nobody-mapped-yet")
    for key in ("headline", "meaning", "next_step"):
        assert "some-new-refusal-nobody-mapped-yet" not in copy[key]


def test_resolve_outcome_state_fails_safe_outside_the_known_vocabulary():
    # Defensive only: build_outcome is never called on an excluded row in
    # the real pipeline (list_audit_events drops those before reaching it),
    # but the function itself must not invent an in-flight/succeeded claim
    # for an action it does not recognise.
    assert audit_events.resolve_outcome_state("some-unknown-action", "whatever") == "failed"
