"""Endpoint tests for GET /api/audit/events (dmfdeploy/dmfdeploy#496 plan).

The four discriminator users from plan §7 AC 5a: a generic allowed/denied
pair cannot tell a per-class gate from a single-gate implementation, so the
fixture below carries every covered class and every excluded class, and the
expected set per user is enumerated here literally — never computed by
calling classify_record/user_passes_gate against this same fixture (that
would be exactly the tautology AC 5a rules out).
"""

from __future__ import annotations

from fastapi.testclient import TestClient
import pytest

import dmf_cms.audit_events as audit_events
from dmf_cms.main import create_app
from dmf_cms.settings import LokiSettings, Settings


OPERATOR_ONLY = ("dmf-console-operator",)
VIEWER_IN_MEDIA_ENGINEERS = ("dmf-console-viewer", "media-engineers")
OPERATOR_IN_MEDIA_ENGINEERS = ("dmf-console-operator", "media-engineers")
VIEWER_ONLY = ("dmf-console-viewer",)


def _client(groups, *, loki_configured=True) -> TestClient:
    settings = Settings(
        runtime_mode="local",
        dev_login_enabled=True,
        dev_groups=groups,
        loki=LokiSettings(url="http://loki.test") if loki_configured else LokiSettings(),
    )
    client = TestClient(create_app(settings=settings))
    client.get("/auth/login", follow_redirects=False)  # dev login -> session
    return client


def _line(
    *, action, actor, role, request_id, target, reason, outcome,
    workload="", capacity="", linked_request_id=None,
) -> str:
    line = (
        f"awx write: action={action} actor={actor} role={role} real_role= "
        f"request_id={request_id} target={target} reason={reason!r} "
        f"outcome={outcome} workload={workload} capacity={capacity}"
    )
    if linked_request_id is not None:
        line += f" linked_request_id={linked_request_id}"
    return "2026-09-03 12:00:00,000 INFO dmf_cms.audit: " + line


# The fixture — every covered class, every excluded class, a real
# auto-rollback join pair, an auto-rollback whose parent does not resolve
# (degrade-not-drop), an unrecognised action, and an unparseable line.
# Enumerated by hand; never generated by calling the code under test.
DEPLOY = _line(
    action="deploy", actor="alice", role="operator", request_id="rid-deploy-1",
    target="wl-a", reason="demo deploy", outcome="dispatched", workload="wl-a",
)
DEPLOY_REFUSED = _line(
    action="deploy", actor="alice", role="operator", request_id="rid-deploy-2",
    target="wl-a", reason="demo deploy retry", outcome="facility-busy",
)
TEARDOWN = _line(
    action="teardown", actor="alice", role="operator", request_id="rid-teardown-1",
    target="wl-b", reason="demo teardown", outcome="dispatched",
)
SWITCH_SOURCE = _line(
    action="switch-source", actor="bob", role="engineer", request_id="rid-switch-1",
    target="receiver-1", reason="demo switch", outcome="active", workload="src-1",
)
AUTO_ROLLBACK = _line(
    action="rollback", actor="system:auto-rollback", role="system", request_id="rid-autorb-1",
    target="run-123", reason="auto: deploy wl-a failed after start (failed_rollback_required)",
    outcome="auto-triggered", linked_request_id="rid-deploy-1",
)
AUTO_ROLLBACK_ORPHAN = _line(
    action="rollback", actor="system:auto-rollback", role="system", request_id="rid-autorb-2",
    target="run-999", reason="auto: deploy wl-z failed after start (failed_rollback_required)",
    outcome="auto-triggered", linked_request_id="rid-nonexistent-parent",
)
FINALISE_PURGE = _line(
    action="finalise-purge", actor="carol", role="operator", request_id="rid-purge-1",
    target="slug-x", reason="demo purge", outcome="dispatched",
)
LAUNCH = _line(
    action="launch", actor="dave", role="engineer", request_id="rid-launch-1",
    target="some-jt", reason="demo launch", outcome="dispatched",
)
VERIFY_DRAIN = _line(
    action="verify-drain", actor="alice", role="operator", request_id="rid-drain-1",
    target="run-456", reason="demo drain", outcome="dispatched",
)
OPERATOR_ROLLBACK = _line(
    action="rollback", actor="alice", role="operator", request_id="rid-oprb-1",
    target="run-789", reason="demo manual rollback", outcome="dispatched",
)
UNRECOGNISED_ACTION = _line(
    action="mystery-action", actor="alice", role="operator", request_id="rid-mystery-1",
    target="wl-a", reason="should never appear", outcome="dispatched",
)
UNPARSEABLE = "2026-09-03 12:00:00,000 INFO dmf_cms.audit: awx write: action=deploy actor=alice request_id=rid-broken"

FIXTURE_LINES = [
    DEPLOY, DEPLOY_REFUSED, TEARDOWN, SWITCH_SOURCE, AUTO_ROLLBACK, AUTO_ROLLBACK_ORPHAN,
    FINALISE_PURGE, LAUNCH, VERIFY_DRAIN, OPERATOR_ROLLBACK, UNRECOGNISED_ACTION, UNPARSEABLE,
]

_VALID_RETENTION_CONFIG = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
"""


def _fake_query_range(*, url, selector, start_ns, end_ns, limit, timeout=10):
    # Plan §4.1: content match, never a logger-field filter — the
    # auto-rollback line is on the module logger, not the audit child
    # logger, so a logger= filter would silently drop a covered class.
    assert '|= "awx write:"' in selector
    assert "logger=" not in selector
    return [{"stream": {}, "values": [[str(i), line] for i, line in enumerate(FIXTURE_LINES)]}]


def _fake_raw_runtime_config(*, url, timeout=10):
    return _VALID_RETENTION_CONFIG


@pytest.fixture(autouse=True)
def _loki(monkeypatch):
    monkeypatch.setattr(audit_events.loki, "query_range", _fake_query_range)
    monkeypatch.setattr(audit_events.loki, "raw_runtime_config", _fake_raw_runtime_config)


def _event_ids(payload) -> set[str]:
    return {e["request_id"] for e in payload["events"]}


# ----------------------------------------------------------------------
# AC 5a — the four discriminator users, equality, not subset/superset.
# ----------------------------------------------------------------------

def test_operator_not_in_media_engineers_sees_deploy_teardown_rollback_not_switch():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert _event_ids(payload) == {
        "rid-deploy-1", "rid-deploy-2", "rid-teardown-1", "rid-autorb-1", "rid-autorb-2",
    }


def test_viewer_in_media_engineers_sees_only_switch_source():
    client = _client(VIEWER_IN_MEDIA_ENGINEERS)
    payload = client.get("/api/audit/events").json()
    assert _event_ids(payload) == {"rid-switch-1"}


def test_operator_in_media_engineers_sees_every_covered_row():
    client = _client(OPERATOR_IN_MEDIA_ENGINEERS)
    payload = client.get("/api/audit/events").json()
    assert _event_ids(payload) == {
        "rid-deploy-1", "rid-deploy-2", "rid-teardown-1", "rid-autorb-1", "rid-autorb-2", "rid-switch-1",
    }


def test_viewer_qualifying_for_neither_sees_the_empty_set():
    client = _client(VIEWER_ONLY)
    payload = client.get("/api/audit/events").json()
    assert _event_ids(payload) == set()


def test_excluded_rows_never_appear_even_for_the_most_privileged_user():
    client = _client(OPERATOR_IN_MEDIA_ENGINEERS)
    payload = client.get("/api/audit/events").json()
    ids = _event_ids(payload)
    for excluded_id in ("rid-purge-1", "rid-launch-1", "rid-drain-1", "rid-oprb-1", "rid-mystery-1", "rid-broken"):
        assert excluded_id not in ids


def test_disclosure_names_the_two_exclusion_reasons_distinctly():
    client = _client(VIEWER_ONLY)
    payload = client.get("/api/audit/events").json()
    by_class = {row["class"]: row["reason"] for row in payload["excluded"]}
    assert by_class["finalise-purge"] == "access"
    assert by_class["launch"] == "scope"
    assert by_class["verify-drain"] == "scope"
    assert by_class["rollback"] == "scope"


# ----------------------------------------------------------------------
# AC 3 / AC 5b — auto-rollback: presence unconditional, label conditional.
# ----------------------------------------------------------------------

def test_auto_rollback_carries_its_parents_workload_when_the_parent_resolves():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-autorb-1")
    assert row["workload"] == "wl-a"
    assert row["outcome"]["state"] == "in_flight"


def test_auto_rollback_still_renders_with_no_workload_when_the_parent_does_not_resolve():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-autorb-2")
    assert row["workload"] is None  # degraded label, NOT a dropped row


# ----------------------------------------------------------------------
# Outcome rendering (AC 2 / AC 2a).
# ----------------------------------------------------------------------

def test_a_refusal_overrides_watched_acceptance_and_never_leaks_raw_at_default():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-deploy-2")
    assert row["outcome"]["state"] == "failed"
    assert row["outcome"]["detail"] == "facility-busy"
    assert "facility-busy" not in row["outcome"]["headline"]


def test_switch_source_carries_a_real_terminal_verdict():
    client = _client(VIEWER_IN_MEDIA_ENGINEERS)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-switch-1")
    assert row["outcome"]["state"] == "succeeded"


def test_a_watched_action_in_flight_never_carries_headline_meaning_next_step():
    # in-flight is acceptance-only — it must not smuggle a verdict-shaped
    # payload in through the failure fields.
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-deploy-1")
    assert row["outcome"] == {"state": "in_flight", "detail": "dispatched"}


# ----------------------------------------------------------------------
# AC 7 — an outage renders differently from an empty history.
# ----------------------------------------------------------------------

def test_loki_unreachable_is_a_distinct_reason_from_a_genuine_empty_history(monkeypatch):
    def _boom(**kwargs):
        raise audit_events.loki.LokiAPIError(0, "connection refused")

    monkeypatch.setattr(audit_events.loki, "query_range", _boom)
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["reason"] == "loki-unreachable"
    assert payload["events"] == []


def test_a_genuinely_empty_history_reads_ok_not_unreachable(monkeypatch):
    monkeypatch.setattr(audit_events.loki, "query_range", lambda **kwargs: [])
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["reason"] == ""
    assert payload["events"] == []


def test_loki_unconfigured_is_its_own_reason_and_makes_no_loki_call(monkeypatch):
    def _fail(**kwargs):
        raise AssertionError("must not call Loki when unconfigured")

    monkeypatch.setattr(audit_events.loki, "query_range", _fail)
    monkeypatch.setattr(audit_events.loki, "raw_runtime_config", _fail)
    client = _client(OPERATOR_ONLY, loki_configured=False)
    payload = client.get("/api/audit/events").json()
    assert payload["reason"] == "loki-unconfigured"
    assert payload["events"] == []


def test_unauthenticated_request_is_401_and_never_calls_loki(monkeypatch):
    def _fail(**kwargs):
        raise AssertionError("must not call Loki for an unauthenticated request")

    monkeypatch.setattr(audit_events.loki, "query_range", _fail)
    settings = Settings(runtime_mode="local", dev_login_enabled=True, loki=LokiSettings(url="http://loki.test"))
    client = TestClient(create_app(settings=settings))
    # deliberately no /auth/login — no session established
    resp = client.get("/api/audit/events")
    assert resp.status_code == 401


# ----------------------------------------------------------------------
# Window (conditions 1/2/3): known when derivable, unknown otherwise, never
# a hardcoded fallback.
# ----------------------------------------------------------------------

def test_window_known_from_the_global_when_no_stream_selector_matches():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["window"]["known"] is True
    assert payload["window"]["seconds"] == 168 * 3600


def test_window_uses_a_matching_stream_selector_over_the_global(monkeypatch):
    monkeypatch.setattr(
        audit_events.loki, "raw_runtime_config",
        lambda **kwargs: (
            "compactor:\n  retention_enabled: true\n"
            "limits_config:\n  retention_period: 168h\n  retention_stream:\n"
            '    - selector: \'{job="dmf-cms/dmf-cms"}\'\n      period: 720h\n      priority: 1\n'
        ),
    )
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["window"]["seconds"] == 720 * 3600


def test_window_unknown_when_retention_not_enforced(monkeypatch):
    monkeypatch.setattr(
        audit_events.loki, "raw_runtime_config",
        lambda **kwargs: "compactor:\n  retention_enabled: false\nlimits_config:\n  retention_period: 168h\n",
    )
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["window"]["known"] is False
    assert payload["window"]["seconds"] is None
    # window unavailability doesn't blank the lane -- events are still real
    assert payload["reason"] == ""


def test_window_unknown_when_config_endpoint_unavailable(monkeypatch):
    def _boom(**kwargs):
        raise audit_events.loki.LokiAPIError(404, "not found")

    monkeypatch.setattr(audit_events.loki, "raw_runtime_config", _boom)
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["window"]["known"] is False
    assert payload["reason"] == ""  # query_range still succeeded independently


# ----------------------------------------------------------------------
# F6 — a bound that binds must be disclosed.
# ----------------------------------------------------------------------

def test_not_capped_when_window_is_known_and_results_are_well_under_the_limit():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["window"]["known"] is True
    assert payload["capped"] is False


def test_capped_when_the_window_could_not_be_derived(monkeypatch):
    # No derived retention window means the query actually ran against the
    # technical ceiling, not a real bound — the response must say so rather
    # than reading as an ordinary, complete history.
    monkeypatch.setattr(
        audit_events.loki, "raw_runtime_config",
        lambda **kwargs: "compactor:\n  retention_enabled: false\nlimits_config:\n  retention_period: 168h\n",
    )
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["window"]["known"] is False
    assert payload["capped"] is True


def test_capped_when_the_result_count_hits_the_technical_limit(monkeypatch):
    # A saturated result count means Loki's own limit may have truncated
    # real rows before this function ever saw them.
    padded = FIXTURE_LINES + [DEPLOY] * (audit_events._MAX_RESULT_LINES - len(FIXTURE_LINES))

    def _saturated(*, url, selector, start_ns, end_ns, limit, timeout=10):
        return [{"stream": {}, "values": [[str(i), line] for i, line in enumerate(padded)]}]

    monkeypatch.setattr(audit_events.loki, "query_range", _saturated)
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert len(padded) == audit_events._MAX_RESULT_LINES
    assert payload["capped"] is True
