"""Endpoint tests for GET /api/audit/events (dmfdeploy/dmfdeploy#496 plan).

The four discriminator users from plan §7 AC 5a: a generic allowed/denied
pair cannot tell a per-class gate from a single-gate implementation, so the
fixture below carries every covered class and every excluded class, and the
expected set per user is enumerated here literally — never computed by
calling classify_record/user_passes_gate against this same fixture (that
would be exactly the tautology AC 5a rules out).
"""

from __future__ import annotations

import logging

from fastapi.testclient import TestClient
import pytest

import dmf_cms.audit_events as audit_events
from dmf_cms.main import _audit_awx_write, _audit_watch_terminal, create_app
from dmf_cms.operations import OperationState
from dmf_cms.security import UserIdentity
from dmf_cms.settings import LokiSettings, Settings


OPERATOR_ONLY = ("dmf-console-operator",)
VIEWER_IN_MEDIA_ENGINEERS = ("dmf-console-viewer", "media-engineers")
OPERATOR_IN_MEDIA_ENGINEERS = ("dmf-console-operator", "media-engineers")
VIEWER_ONLY = ("dmf-console-viewer",)


def _client(groups, *, loki_configured=True) -> TestClient:
    settings = Settings(
        runtime_mode="local",
        dev_login_enabled=True,
        dev_groups=groups,
        loki=LokiSettings(url="http://loki.test") if loki_configured else LokiSettings(),
    )
    # gate round 1 (codex P2): /api/audit/events now reads
    # app.state.operations.ttl_seconds, which the app's lifespan (not
    # __init__) populates — TestClient only runs lifespan startup as a
    # context manager. Every caller here uses the returned client for the
    # rest of its own test body (never within a nested `with` of its own,
    # unlike test_autoscale_operations.py's per-test pattern), so entering
    # the context manager manually and never exiting it is the one way to
    # get real startup behavior without restructuring every call site in
    # this file — same live app.state.operations instance either way, and
    # a test process that exits at suite end has nothing to clean up.
    client = TestClient(create_app(settings=settings)).__enter__()
    client.get("/auth/login", follow_redirects=False)  # dev login -> session
    return client


def _line(
    *, action, actor, role, request_id, target, reason, outcome,
    workload="", capacity="", linked_request_id=None,
) -> str:
    # dmfdeploy/dmf-cms#140: the fmt=2 grammar -- target/actor/reason/
    # workload/capacity are quoted (%r), exactly as the real emitter
    # writes them; action/role/real_role/request_id/outcome stay plain.
    line = (
        f"awx write: fmt=2 action={action} actor={actor!r} role={role} real_role= "
        f"request_id={request_id} target={target!r} reason={reason!r} "
        f"outcome={outcome} workload={workload!r} capacity={capacity!r}"
    )
    if linked_request_id is not None:
        line += f" linked_request_id={linked_request_id}"
    return "2026-09-03 12:00:00,000 INFO dmf_cms.audit: " + line


# The fixture — every covered class, every excluded class, a real
# auto-rollback join pair, an auto-rollback whose parent does not resolve
# (degrade-not-drop), an unrecognised action, and an unparseable line.
# Enumerated by hand; never generated by calling the code under test.
DEPLOY = _line(
    action="deploy", actor="alice", role="operator", request_id="rid-deploy-1",
    target="wl-a", reason="demo deploy", outcome="dispatched", workload="wl-a",
)
DEPLOY_REFUSED = _line(
    action="deploy", actor="alice", role="operator", request_id="rid-deploy-2",
    target="wl-a", reason="demo deploy retry", outcome="facility-busy",
)
TEARDOWN = _line(
    action="teardown", actor="alice", role="operator", request_id="rid-teardown-1",
    target="wl-b", reason="demo teardown", outcome="dispatched",
)
SWITCH_SOURCE = _line(
    action="switch-source", actor="bob", role="engineer", request_id="rid-switch-1",
    target="receiver-1", reason="demo switch", outcome="active", workload="src-1",
)
AUTO_ROLLBACK = _line(
    action="rollback", actor="system:auto-rollback", role="system", request_id="rid-autorb-1",
    target="run-123", reason="auto: deploy wl-a failed after start (failed_rollback_required)",
    outcome="auto-triggered", linked_request_id="rid-deploy-1",
)
AUTO_ROLLBACK_ORPHAN = _line(
    action="rollback", actor="system:auto-rollback", role="system", request_id="rid-autorb-2",
    target="run-999", reason="auto: deploy wl-z failed after start (failed_rollback_required)",
    outcome="auto-triggered", linked_request_id="rid-nonexistent-parent",
)
AUTO_ROLLBACK_TERMINAL = _line(
    action="rollback", actor="system:job-watch", role="system", request_id="rid-autorb-1-watch",
    target="run-123", reason="job watch: rollback on run-123 reached terminal state run_complete",
    outcome="run_complete:rollback_complete", linked_request_id="rid-autorb-1",
)
AUTO_ROLLBACK_INITIAL_TERMINAL = _line(
    action="rollback", actor="system:job-watch", role="system", request_id="rid-autorb-1-initial-watch",
    target="run-123", reason="job watch: rollback on run-123 reached terminal state rollback_incomplete",
    outcome="rollback_incomplete:rollback_incomplete", linked_request_id="rid-autorb-1",
)
AUTO_ROLLBACK_ALREADY_IN_PROGRESS = _line(
    action="rollback", actor="system:auto-rollback", role="system", request_id="rid-autorb-existing",
    target="run-existing", reason="auto: rollback already in progress", outcome="already-in-progress",
    linked_request_id="rid-deploy-1",
)
AUTO_ROLLBACK_ALREADY_IN_PROGRESS_TERMINAL = _line(
    action="rollback", actor="system:job-watch", role="system", request_id="rid-autorb-existing-watch",
    target="run-existing", reason="job watch: rollback on run-existing reached terminal state run_complete",
    outcome="run_complete:rollback_complete", linked_request_id="rid-autorb-existing",
)
AUTO_ROLLBACK_UNKNOWN = _line(
    action="rollback", actor="system:auto-rollback", role="system", request_id="rid-autorb-3",
    target="run-456", reason="auto: deploy wl-c failed after start (failed_rollback_required)",
    outcome="auto-triggered", linked_request_id="rid-deploy-1",
)
AUTO_ROLLBACK_UNKNOWN_TERMINAL = _line(
    action="rollback", actor="system:job-watch", role="system", request_id="rid-autorb-3-watch",
    target="run-456", reason="job watch: rollback on run-456 reached terminal state run_status_unknown",
    outcome="run_status_unknown", linked_request_id="rid-autorb-3",
)
FINALISE_PURGE = _line(
    action="finalise-purge", actor="carol", role="operator", request_id="rid-purge-1",
    target="slug-x", reason="demo purge", outcome="dispatched",
)
LAUNCH = _line(
    action="launch", actor="dave", role="engineer", request_id="rid-launch-1",
    target="some-jt", reason="demo launch", outcome="dispatched",
)
VERIFY_DRAIN = _line(
    action="verify-drain", actor="alice", role="operator", request_id="rid-drain-1",
    target="run-456", reason="demo drain", outcome="dispatched",
)
OPERATOR_ROLLBACK = _line(
    action="rollback", actor="alice", role="operator", request_id="rid-oprb-1",
    target="run-789", reason="demo manual rollback", outcome="dispatched",
)
UNRECOGNISED_ACTION = _line(
    action="mystery-action", actor="alice", role="operator", request_id="rid-mystery-1",
    target="wl-a", reason="should never appear", outcome="dispatched",
)
UNPARSEABLE = "2026-09-03 12:00:00,000 INFO dmf_cms.audit: awx write: action=deploy actor=alice request_id=rid-broken"
# dmfdeploy/dmf-cms#140: legacy is dropped, not parsed by a fallback
# grammar (operator decision) — so a truncated/malformed line, WITH or
# WITHOUT a truncated fmt=2 marker, is unparseable for the same reason
# UNPARSEABLE above already is, and needs no dedicated fixture. What DOES
# still need coverage on the new format: codex R496-C P1-2's property
# that a genuinely blank `outcome` value (the row otherwise complete and
# well-formed) renders as an honest "unknown", never a forged verdict —
# reachable on this grammar as an outcome that's simply empty, not as a
# truncation (any truncation of a REQUIRED field now drops the whole row
# — there is no partial-render fallback left to test).
DEPLOY_BLANK_OUTCOME = _line(
    action="deploy", actor="erin", role="operator", request_id="rid-deploy-corrupted",
    target="wl-c", reason="outcome field lost upstream", outcome="",
)

# dmfdeploy/dmfdeploy#419/#554: the terminal-outcome join — a dispatch row
# plus a SEPARATE system:job-watch record correlating back to it via
# linked_request_id, exactly the auto-rollback join's own shape (see
# AUTO_ROLLBACK above), reused for a second (action, actor) pair.
DEPLOY_TERMINAL_SUCCEEDED = _line(
    action="deploy", actor="frank", role="operator", request_id="rid-deploy-term-1",
    target="wl-d", reason="demo deploy with a confirmed outcome", outcome="dispatched", workload="wl-d",
)
DEPLOY_TERMINAL_SUCCEEDED_JOIN = _line(
    action="deploy", actor="system:job-watch", role="system", request_id="rid-deploy-term-1-watch",
    target="wl-d", reason="job watch: deploy on wl-d reached terminal state run_complete",
    outcome="run_complete", linked_request_id="rid-deploy-term-1",
)
TEARDOWN_TERMINAL_FAILED = _line(
    action="teardown", actor="frank", role="operator", request_id="rid-teardown-term-1",
    target="wl-e", reason="demo teardown with a confirmed failure", outcome="dispatched",
)
TEARDOWN_TERMINAL_FAILED_JOIN = _line(
    action="teardown", actor="system:job-watch", role="system", request_id="rid-teardown-term-1-watch",
    target="wl-e", reason="job watch: teardown on wl-e reached terminal state run_failed",
    outcome="run_failed:pre-mutation-refused", linked_request_id="rid-teardown-term-1",
)
# The watcher's own give-up path (TTL/lost/crash) — no confirmed job read,
# so the join's own outcome is run_status_unknown, never a guessed verdict.
DEPLOY_TERMINAL_WATCHER_GAVE_UP = _line(
    action="deploy", actor="frank", role="operator", request_id="rid-deploy-term-2",
    target="wl-f", reason="demo deploy whose watcher gave up", outcome="dispatched",
)
DEPLOY_TERMINAL_WATCHER_GAVE_UP_JOIN = _line(
    action="deploy", actor="system:job-watch", role="system", request_id="rid-deploy-term-2-watch",
    target="wl-f", reason="job watch: deploy on wl-f reached terminal state run_status_unknown",
    outcome="run_status_unknown", linked_request_id="rid-deploy-term-2",
)

# gate round 1 (codex P1): a real, authenticated user whose IdP subject
# HAPPENS to collide with the reserved system:job-watch actor literal,
# doing an ordinary deploy of their own -- role=operator, never "system"
# (a real user's role can never be that value; see classify_record's own
# docstring). Proves the fix is role-gated, not actor-gated: this row
# must survive, classified as a normal deploy, never dropped.
COLLIDING_ACTOR_REAL_USER_DEPLOY = _line(
    action="deploy", actor="system:job-watch", role="operator", request_id="rid-collision-1",
    target="wl-g", reason="a real user whose subject collides with the reserved actor", outcome="dispatched",
    workload="wl-g",
)

# gate round 4 (lkirc B1): a single deploy REQUEST that shares one
# request_id across TWO rows — an L3 preflight acceptance (capacity-
# skipped, main.py's _l3_preflight) and the later real dispatch — exactly
# main.py:485-490's own shape, plus a terminal join for that same
# request_id. Proves the join lands on the dispatch row alone; the
# preflight row must keep its own distinct result, never overwritten with
# a verdict it never described.
DEPLOY_PREFLIGHT_SKIPPED_SHARING_REQUEST_ID = _line(
    action="deploy", actor="frank", role="operator", request_id="rid-preflight-1",
    target="wl-h", reason="L3 disabled, preflight skipped", outcome="capacity-skipped",
)
DEPLOY_DISPATCH_SHARING_REQUEST_ID = _line(
    action="deploy", actor="frank", role="operator", request_id="rid-preflight-1",
    target="wl-h", reason="the same request's real dispatch", outcome="dispatched", workload="wl-h",
)
DEPLOY_PREFLIGHT_DISPATCH_TERMINAL_JOIN = _line(
    action="deploy", actor="system:job-watch", role="system", request_id="rid-preflight-1-watch",
    target="wl-h", reason="job watch: deploy on wl-h reached terminal state run_complete",
    outcome="run_complete", linked_request_id="rid-preflight-1",
)

# gate round 5 (lkirc): a reattach row is written by a FRESH, different
# request_id (a new HTTP request) but concerns the SAME run as the
# original dispatch — main.py's deploy/teardown reattach call sites now
# carry that run's own stable identity (the original op's request_id) via
# linked_request_id. Two reattaches on the SAME run (rid-run-1), by two
# DIFFERENT users, prove the fix generalizes past a single reattach.
DEPLOY_ORIGINAL_DISPATCH_FOR_REATTACH = _line(
    action="deploy", actor="frank", role="operator", request_id="rid-run-1",
    target="wl-i", reason="the original dispatch", outcome="dispatched", workload="wl-i",
)
DEPLOY_REATTACH_1 = _line(
    action="deploy", actor="grace", role="operator", request_id="rid-reattach-1a",
    target="wl-i", reason="a browser refresh reattaches", outcome="reattached",
    linked_request_id="rid-run-1",
)
DEPLOY_REATTACH_2 = _line(
    action="deploy", actor="heidi", role="operator", request_id="rid-reattach-1b",
    target="wl-i", reason="a second reattach, a different user", outcome="reattached",
    linked_request_id="rid-run-1",
)
DEPLOY_RUN_1_TERMINAL_JOIN = _line(
    action="deploy", actor="system:job-watch", role="system", request_id="rid-run-1-watch",
    target="wl-i", reason="job watch: deploy on wl-i reached terminal state run_complete",
    outcome="run_complete", linked_request_id="rid-run-1",
)
TEARDOWN_ORIGINAL_DISPATCH_FOR_REATTACH = _line(
    action="teardown", actor="frank", role="operator", request_id="rid-run-2",
    target="wl-j", reason="the original teardown dispatch", outcome="dispatched",
)
TEARDOWN_REATTACH_1 = _line(
    action="teardown", actor="grace", role="operator", request_id="rid-reattach-2a",
    target="wl-j", reason="a reattach", outcome="reattached", linked_request_id="rid-run-2",
)
TEARDOWN_RUN_2_TERMINAL_JOIN = _line(
    action="teardown", actor="system:job-watch", role="system", request_id="rid-run-2-watch",
    target="wl-j", reason="job watch: teardown on wl-j reached terminal state run_failed",
    outcome="run_failed", linked_request_id="rid-run-2",
)

# gate round 6 (lkirc): the SAME defect as round 5's reattach fixtures,
# at the SYNC already-active path — main.py:5143/:5392 (deploy/teardown)
# now carry the run's own stable identity too. Two already-active rows on
# the SAME run (rid-run-3), proving repeated sync reattaches all resolve.
DEPLOY_ORIGINAL_DISPATCH_FOR_ALREADY_ACTIVE = _line(
    action="deploy", actor="frank", role="operator", request_id="rid-run-3",
    target="wl-k", reason="the original dispatch", outcome="dispatched", workload="wl-k",
)
DEPLOY_ALREADY_ACTIVE_1 = _line(
    action="deploy", actor="grace", role="operator", request_id="rid-active-3a",
    target="wl-k", reason="a sync already-active hit", outcome="already-active",
    linked_request_id="rid-run-3",
)
DEPLOY_ALREADY_ACTIVE_2 = _line(
    action="deploy", actor="heidi", role="operator", request_id="rid-active-3b",
    target="wl-k", reason="a second sync already-active hit", outcome="already-active",
    linked_request_id="rid-run-3",
)
DEPLOY_RUN_3_TERMINAL_JOIN = _line(
    action="deploy", actor="system:job-watch", role="system", request_id="rid-run-3-watch",
    target="wl-k", reason="job watch: deploy on wl-k reached terminal state run_complete",
    outcome="run_complete", linked_request_id="rid-run-3",
)
TEARDOWN_ORIGINAL_DISPATCH_FOR_ALREADY_ACTIVE = _line(
    action="teardown", actor="frank", role="operator", request_id="rid-run-4",
    target="wl-l", reason="the original teardown dispatch", outcome="dispatched",
)
TEARDOWN_ALREADY_ACTIVE_1 = _line(
    action="teardown", actor="grace", role="operator", request_id="rid-active-4a",
    target="wl-l", reason="a sync already-active hit", outcome="already-active",
    linked_request_id="rid-run-4",
)
TEARDOWN_RUN_4_TERMINAL_JOIN = _line(
    action="teardown", actor="system:job-watch", role="system", request_id="rid-run-4-watch",
    target="wl-l", reason="job watch: teardown on wl-l reached terminal state run_failed",
    outcome="run_failed", linked_request_id="rid-run-4",
)

FIXTURE_LINES = [
    DEPLOY, DEPLOY_REFUSED, TEARDOWN, SWITCH_SOURCE, AUTO_ROLLBACK, AUTO_ROLLBACK_ORPHAN,
    AUTO_ROLLBACK_INITIAL_TERMINAL, AUTO_ROLLBACK_TERMINAL,
    AUTO_ROLLBACK_ALREADY_IN_PROGRESS, AUTO_ROLLBACK_ALREADY_IN_PROGRESS_TERMINAL,
    AUTO_ROLLBACK_UNKNOWN, AUTO_ROLLBACK_UNKNOWN_TERMINAL,
    FINALISE_PURGE, LAUNCH, VERIFY_DRAIN, OPERATOR_ROLLBACK, UNRECOGNISED_ACTION, UNPARSEABLE,
    DEPLOY_BLANK_OUTCOME,
    DEPLOY_TERMINAL_SUCCEEDED, DEPLOY_TERMINAL_SUCCEEDED_JOIN,
    TEARDOWN_TERMINAL_FAILED, TEARDOWN_TERMINAL_FAILED_JOIN,
    DEPLOY_TERMINAL_WATCHER_GAVE_UP, DEPLOY_TERMINAL_WATCHER_GAVE_UP_JOIN,
    COLLIDING_ACTOR_REAL_USER_DEPLOY,
    DEPLOY_PREFLIGHT_SKIPPED_SHARING_REQUEST_ID, DEPLOY_DISPATCH_SHARING_REQUEST_ID,
    DEPLOY_PREFLIGHT_DISPATCH_TERMINAL_JOIN,
    DEPLOY_ORIGINAL_DISPATCH_FOR_REATTACH, DEPLOY_REATTACH_1, DEPLOY_REATTACH_2, DEPLOY_RUN_1_TERMINAL_JOIN,
    TEARDOWN_ORIGINAL_DISPATCH_FOR_REATTACH, TEARDOWN_REATTACH_1, TEARDOWN_RUN_2_TERMINAL_JOIN,
    DEPLOY_ORIGINAL_DISPATCH_FOR_ALREADY_ACTIVE, DEPLOY_ALREADY_ACTIVE_1, DEPLOY_ALREADY_ACTIVE_2,
    DEPLOY_RUN_3_TERMINAL_JOIN,
    TEARDOWN_ORIGINAL_DISPATCH_FOR_ALREADY_ACTIVE, TEARDOWN_ALREADY_ACTIVE_1, TEARDOWN_RUN_4_TERMINAL_JOIN,
]

_VALID_RETENTION_CONFIG = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
"""


def _fake_query_range(*, url, selector, start_ns, end_ns, limit, timeout=10):
    # Plan §4.1: content match, never a logger-field filter — the
    # auto-rollback line is on the module logger, not the audit child
    # logger, so a logger= filter would silently drop a covered class.
    assert '|= "awx write:"' in selector
    assert "logger=" not in selector
    return [{"stream": {}, "values": [[str(i), line] for i, line in enumerate(FIXTURE_LINES)]}]


def _fake_raw_runtime_config(*, url, timeout=10):
    return _VALID_RETENTION_CONFIG


@pytest.fixture(autouse=True)
def _loki(monkeypatch):
    monkeypatch.setattr(audit_events.loki, "query_range", _fake_query_range)
    monkeypatch.setattr(audit_events.loki, "raw_runtime_config", _fake_raw_runtime_config)


# gate round 1 (codex P2): list_audit_events now ages a stale, never-joined
# in_flight row using REAL wall-clock time by default (`now_ns=None` ->
# `time.time_ns()`) against `app.state.operations.ttl_seconds` (3600s).
# FIXTURE_LINES' own `ts_ns_str` values are `str(i)` -- i.e. a handful of
# NANOSECONDS after the Unix epoch -- so left unpinned, every existing
# in_flight fixture row would already read as ~decades stale against any
# real "now" and every pre-existing in_flight assertion in this file would
# start failing regardless of what day it is. Freezing "now" here to a
# small, fixed offset (5s -- far inside the 3600s bound) keeps every
# EXISTING test's behavior exactly what it was before this round; the two
# dedicated aging tests below override this per-test to push a row's own
# age past the bound on purpose.
@pytest.fixture(autouse=True)
def _frozen_now(monkeypatch):
    monkeypatch.setattr(audit_events.time, "time_ns", lambda: 5_000_000_000)


def _event_ids(payload) -> set[str]:
    return {e["request_id"] for e in payload["events"]}


# ----------------------------------------------------------------------
# AC 5a — the four discriminator users, equality, not subset/superset.
# ----------------------------------------------------------------------

def test_operator_not_in_media_engineers_sees_deploy_teardown_rollback_not_switch():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert _event_ids(payload) == {
        "rid-deploy-1", "rid-deploy-2", "rid-teardown-1", "rid-autorb-1", "rid-autorb-2",
        "rid-autorb-3", "rid-autorb-existing",
        "rid-deploy-corrupted",
        "rid-deploy-term-1", "rid-teardown-term-1", "rid-deploy-term-2",
        "rid-collision-1", "rid-preflight-1",
        "rid-run-1", "rid-reattach-1a", "rid-reattach-1b",
        "rid-run-2", "rid-reattach-2a",
        "rid-run-3", "rid-active-3a", "rid-active-3b",
        "rid-run-4", "rid-active-4a",
    }


def test_viewer_in_media_engineers_sees_only_switch_source():
    client = _client(VIEWER_IN_MEDIA_ENGINEERS)
    payload = client.get("/api/audit/events").json()
    assert _event_ids(payload) == {"rid-switch-1"}


def test_operator_in_media_engineers_sees_every_covered_row():
    client = _client(OPERATOR_IN_MEDIA_ENGINEERS)
    payload = client.get("/api/audit/events").json()
    assert _event_ids(payload) == {
        "rid-deploy-1", "rid-deploy-2", "rid-teardown-1", "rid-autorb-1", "rid-autorb-2", "rid-switch-1",
        "rid-autorb-3", "rid-autorb-existing",
        "rid-deploy-corrupted",
        "rid-deploy-term-1", "rid-teardown-term-1", "rid-deploy-term-2",
        "rid-collision-1", "rid-preflight-1",
        "rid-run-1", "rid-reattach-1a", "rid-reattach-1b",
        "rid-run-2", "rid-reattach-2a",
        "rid-run-3", "rid-active-3a", "rid-active-3b",
        "rid-run-4", "rid-active-4a",
    }


def test_viewer_qualifying_for_neither_sees_the_empty_set():
    client = _client(VIEWER_ONLY)
    payload = client.get("/api/audit/events").json()
    assert _event_ids(payload) == set()


def test_excluded_rows_never_appear_even_for_the_most_privileged_user():
    client = _client(OPERATOR_IN_MEDIA_ENGINEERS)
    payload = client.get("/api/audit/events").json()
    ids = _event_ids(payload)
    for excluded_id in ("rid-purge-1", "rid-launch-1", "rid-drain-1", "rid-oprb-1", "rid-mystery-1", "rid-broken"):
        assert excluded_id not in ids


def test_disclosure_names_the_two_exclusion_reasons_distinctly():
    client = _client(VIEWER_ONLY)
    payload = client.get("/api/audit/events").json()
    by_class = {row["class"]: row["reason"] for row in payload["excluded"]}
    assert by_class["finalise-purge"] == "access"
    assert by_class["launch"] == "scope"
    assert by_class["verify-drain"] == "scope"
    assert by_class["rollback"] == "scope"


# ----------------------------------------------------------------------
# AC 3 / AC 5b — auto-rollback: presence unconditional, label conditional.
# ----------------------------------------------------------------------

def test_auto_rollback_carries_its_parents_workload_when_the_parent_resolves():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-autorb-1")
    assert row["workload"] == "wl-a"


def test_auto_rollback_still_renders_with_no_workload_when_the_parent_does_not_resolve():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-autorb-2")
    assert row["workload"] is None  # degraded label, NOT a dropped row


def test_auto_rollback_terminal_join_renders_the_rollback_outcome():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-autorb-1")
    assert row["outcome"] == {"state": "succeeded", "detail": "run_complete"}
    assert "rid-autorb-1-watch" not in _event_ids(payload)


def test_auto_rollback_already_in_progress_joins_the_existing_operations_terminal_outcome():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-autorb-existing")
    assert row["outcome"] == {"state": "succeeded", "detail": "run_complete"}
    assert "rid-autorb-existing-watch" not in _event_ids(payload)


def test_auto_rollback_with_unobserved_terminal_outcome_reads_unknown():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-autorb-3")
    assert row["outcome"]["state"] == "unknown"


# ----------------------------------------------------------------------
# Terminal-outcome join (dmfdeploy/dmfdeploy#419/#554) — the deploy/
# teardown "Deploy dispatched for X" -> "Deploy succeeded/failed for X"
# resolution, end to end.
# ----------------------------------------------------------------------

def test_a_deploy_with_a_terminal_join_renders_succeeded_not_in_flight():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-deploy-term-1")
    assert row["outcome"] == {"state": "succeeded", "detail": "run_complete"}


def test_a_teardown_with_a_terminal_join_renders_failed_with_the_launcher_marker_as_detail():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-teardown-term-1")
    assert row["outcome"]["state"] == "failed"
    assert row["outcome"]["detail"] == "pre-mutation-refused"
    for key in ("headline", "meaning", "next_step"):
        assert row["outcome"][key]


def test_the_job_watch_join_record_never_renders_as_its_own_row():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    request_ids = {e["request_id"] for e in payload["events"]}
    assert "rid-deploy-term-1-watch" not in request_ids
    assert "rid-teardown-term-1-watch" not in request_ids
    assert "rid-deploy-term-2-watch" not in request_ids


def test_a_watcher_give_up_join_renders_unknown_never_a_silent_dispatched_or_success():
    # The watcher's own give-up path (TTL timeout / lost get_job calls /
    # an unexpected crash) — carries no confirmed job read, so the join
    # itself is run_status_unknown. Must render as the lane's honest
    # 'unknown', never a guessed success or failure.
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-deploy-term-2")
    assert row["outcome"]["state"] == "unknown"
    assert row["outcome"]["state"] not in ("succeeded", "in_flight")


def test_a_dispatch_row_with_no_terminal_join_at_all_stays_in_flight_never_a_guessed_success():
    # dmfdeploy/dmfdeploy#419's documented residual gap: the watcher runs
    # in-process on a single replica, so a console restart mid-job loses
    # the watch and that row NEVER receives a terminal join — DEPLOY's own
    # fixture row above carries no join. The honesty requirement this
    # whole feature exists for: this must never render as succeeded.
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-deploy-1")
    assert row["outcome"]["state"] == "in_flight"
    assert row["outcome"]["state"] != "succeeded"


def test_gate_round_1_codex_p1_a_real_user_colliding_with_the_reserved_actor_still_gets_their_row():
    # codex P1: a genuine user's deploy row, whose actor happens to equal
    # the reserved system:job-watch literal (role=operator -- a real
    # user's role can never be "system"), must survive end to end,
    # classified as an ordinary deploy -- never dropped, never folded into
    # the join-only machinery.
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-collision-1")
    assert row["class"] == "deploy"
    assert row["actor"] == "system:job-watch"
    assert row["outcome"]["state"] == "in_flight"


def test_gate_round_2_codex_f5_producer_to_reader_invariant_end_to_end(monkeypatch, caplog):
    # gate round 2 (codex F5): every OTHER test in this file hand-builds
    # its fixture lines, role= values included -- that proves the READER's
    # logic but nothing about whether the REAL producers actually emit
    # what the P1 invariant assumes. This one drives the real
    # _audit_awx_write (a colliding user-initiated deploy, and a genuine
    # one) and the real _audit_watch_terminal (its terminal join), captures
    # their ACTUAL emitted lines, and reads them back through the REAL
    # /api/audit/events endpoint -- not a second hand-written copy of the
    # same shape.
    request_obj = _FakeRequest()
    colliding_user = UserIdentity(
        subject="system:job-watch", display_name="Collider", email="collider@dmf.example.com",
        role="operator", groups=(),
    )
    dispatching_user = UserIdentity(
        subject="frank", display_name="Frank", email="frank@dmf.example.com",
        role="operator", groups=(),
    )
    with caplog.at_level(logging.INFO, logger="dmf_cms.audit"):
        # A real user whose subject collides with the reserved actor,
        # doing a genuine deploy of their own.
        _audit_awx_write(
            request_obj, colliding_user, action="deploy", target="wl-real-collision",
            request_id="rid-real-collision", reason="a real emitted collision",
            outcome="dispatched", workload="wl-real-collision",
        )
        # A genuine dispatch...
        _audit_awx_write(
            request_obj, dispatching_user, action="deploy", target="wl-real-dispatch",
            request_id="rid-real-dispatch", reason="a real dispatch",
            outcome="dispatched", workload="wl-real-dispatch",
        )
        # ...and its REAL terminal join, via the console's own emitter.
        _audit_watch_terminal("deploy", "wl-real-dispatch", "rid-real-dispatch", OperationState.RUN_COMPLETE, None)

    real_lines = [
        _formatted_line(r) for r in caplog.records
        if r.name == "dmf_cms.audit" and r.getMessage().startswith("awx write:")
    ]
    assert len(real_lines) == 3  # sanity: all three calls above actually emitted

    def _real_query_range(*, url, selector, start_ns, end_ns, limit, timeout=10):
        return [{"stream": {}, "values": [[str(i), line] for i, line in enumerate(real_lines)]}]

    monkeypatch.setattr(audit_events.loki, "query_range", _real_query_range)

    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()

    # The colliding row survives, correctly classified -- never dropped.
    collision_row = next(e for e in payload["events"] if e["request_id"] == "rid-real-collision")
    assert collision_row["class"] == "deploy"

    # The genuine terminal join resolves onto its dispatch row.
    dispatch_row = next(e for e in payload["events"] if e["request_id"] == "rid-real-dispatch")
    assert dispatch_row["outcome"] == {"state": "succeeded", "detail": "run_complete"}

    # The join record itself never renders as a THIRD row.
    assert {e["request_id"] for e in payload["events"]} == {"rid-real-collision", "rid-real-dispatch"}


def test_gate_round_2_codex_f2_a_missing_operations_store_never_masquerades_as_a_loki_outage(monkeypatch, caplog):
    # codex F2: app.state.operations only exists once the app's ASGI
    # lifespan has actually run -- a TestClient invoked WITHOUT that
    # startup (deliberately NOT using __enter__ here, unlike this file's
    # own _client() helper as of gate round 1) must not fall into the
    # endpoint's generic except-Exception handler and mislabel a real,
    # working Loki read as "Loki itself is unreachable".
    monkeypatch.setattr(audit_events.time, "time_ns", lambda: 10_000 * 1_000_000_000)  # would age, if aging ran
    settings = Settings(
        runtime_mode="local", dev_login_enabled=True, dev_groups=OPERATOR_ONLY,
        loki=LokiSettings(url="http://loki.test"),
    )
    client = TestClient(create_app(settings=settings))  # deliberately NOT entered -- no lifespan, no app.state.operations
    client.get("/auth/login", follow_redirects=False)

    with caplog.at_level(logging.ERROR, logger="dmf_cms.main"):
        payload = client.get("/api/audit/events").json()

    # The real read still succeeds -- NOT the Loki-outage shape.
    assert payload["reason"] == ""
    row = next(e for e in payload["events"] if e["request_id"] == "rid-deploy-1")
    # Aging fails OPEN when the bound can't be resolved -- the row stays
    # in_flight even though "now" above was pushed well past the bound
    # that WOULD have aged it had app.state.operations been available
    # (see test_gate_round_1_codex_p2_a_stale_never_joined_row_ages_into_
    # the_honest_unknown, same now_ns, same row, opposite outcome).
    assert row["outcome"]["state"] == "in_flight"

    # Never silent: a distinct, loudly-logged condition, not folded into
    # the generic "read failed" warning either.
    messages = [r.getMessage() for r in caplog.records]
    assert any("app.state.operations is unavailable" in m for m in messages)
    assert not any("audit events: read failed" in m for m in messages)


def test_gate_round_1_codex_p2_a_stale_never_joined_row_ages_into_the_honest_unknown(monkeypatch):
    # codex P2: a dispatch row that NEVER receives a terminal join (a
    # console restart mid-watch, a crashed/cancelled watcher -- from this
    # read path they are indistinguishable, see _age_stale_in_flight's own
    # docstring) must stop claiming to still be in flight once it has
    # provably outlived any watcher that could still be attached to it.
    # "now" pushed well past ttl_seconds=3600 relative to the fixture
    # rows' own near-epoch ts_ns -- rid-deploy-1 (DEPLOY, no join) is the
    # discriminator here.
    monkeypatch.setattr(audit_events.time, "time_ns", lambda: 10_000 * 1_000_000_000)
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-deploy-1")
    assert row["outcome"]["state"] == "unknown"
    assert row["outcome"]["state"] not in ("in_flight", "succeeded")


def test_gate_round_1_codex_p2_inside_the_bound_still_reads_in_flight(monkeypatch):
    # The other half of the discriminating pair -- proves the aging fix
    # does not lie in the OTHER direction by making the bound fire
    # unconditionally. A row still comfortably inside ttl_seconds=3600
    # (here: 60s old) must keep reading in_flight, unchanged.
    monkeypatch.setattr(audit_events.time, "time_ns", lambda: 60 * 1_000_000_000)
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-deploy-1")
    assert row["outcome"]["state"] == "in_flight"


def test_gate_round_1_codex_p2_a_join_resolved_row_is_never_aged_regardless_of_now(monkeypatch):
    # A row a terminal join already resolved must never be reconsidered by
    # the age check, no matter how stale it looks -- aging only ever
    # applies to the "we genuinely don't have an answer" case.
    monkeypatch.setattr(audit_events.time, "time_ns", lambda: 10_000 * 1_000_000_000)
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-deploy-term-1")
    assert row["outcome"] == {"state": "succeeded", "detail": "run_complete"}


def test_gate_round_4_lkirc_b1_a_preflight_row_keeps_its_own_outcome_the_dispatch_row_alone_carries_the_verdict():
    # lkirc B1: DEPLOY_PREFLIGHT_SKIPPED_SHARING_REQUEST_ID and
    # DEPLOY_DISPATCH_SHARING_REQUEST_ID share ONE request_id
    # (rid-preflight-1) — exactly main.py's own _l3_preflight shape
    # (capacity-skipped, then the real dispatch, same request). A
    # terminal join for that request_id must resolve onto the DISPATCH
    # row only; the preflight row must keep reading its own
    # capacity-skipped acceptance, never overwritten with a verdict it
    # never described, and never duplicated into a second "succeeded" row.
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    rows = [e for e in payload["events"] if e["request_id"] == "rid-preflight-1"]
    assert len(rows) == 2  # both rows present — request_id is not a per-row identity

    dispatch_rows = [r for r in rows if r["reason"] == "the same request's real dispatch"]
    preflight_rows = [r for r in rows if r["reason"] == "L3 disabled, preflight skipped"]
    assert len(dispatch_rows) == 1
    assert len(preflight_rows) == 1

    # The dispatch row alone carries the confirmed verdict.
    assert dispatch_rows[0]["outcome"] == {"state": "succeeded", "detail": "run_complete"}

    # The preflight row keeps its OWN outcome — its own dispatch-time
    # acceptance token, never the job's verdict.
    assert preflight_rows[0]["outcome"] == {"state": "in_flight", "detail": "capacity-skipped"}

    # No duplicate verdict: exactly ONE row for this request_id reads
    # 'succeeded' — never two.
    succeeded_count = sum(1 for r in rows if r["outcome"]["state"] == "succeeded")
    assert succeeded_count == 1


def test_gate_round_5_lkirc_a_reattached_deploy_receives_the_same_terminal_outcome_as_the_original():
    # lkirc: request_id identifies the HTTP REQUEST that wrote a row, not
    # the RUN it concerns. DEPLOY_REATTACH_1/_2 are written by fresh,
    # DIFFERENT request_ids (their own) but concern the SAME run as
    # DEPLOY_ORIGINAL_DISPATCH_FOR_REATTACH (rid-run-1) — main.py's
    # reattach call sites now carry that run's own stable identity via
    # linked_request_id, so the terminal join (also keyed to rid-run-1)
    # must resolve onto all three rows identically.
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    original = next(e for e in payload["events"] if e["request_id"] == "rid-run-1")
    reattach_1 = next(e for e in payload["events"] if e["request_id"] == "rid-reattach-1a")
    reattach_2 = next(e for e in payload["events"] if e["request_id"] == "rid-reattach-1b")
    expected = {"state": "succeeded", "detail": "run_complete"}
    assert original["outcome"] == expected
    assert reattach_1["outcome"] == expected
    assert reattach_2["outcome"] == expected


def test_gate_round_5_lkirc_a_reattached_teardown_receives_the_same_terminal_outcome_as_the_original():
    # Same fix, the other action class lkirc explicitly named (both call
    # sites, not just one).
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    original = next(e for e in payload["events"] if e["request_id"] == "rid-run-2")
    reattach = next(e for e in payload["events"] if e["request_id"] == "rid-reattach-2a")
    assert original["outcome"]["state"] == "failed"
    assert reattach["outcome"] == original["outcome"]


def test_gate_round_5_lkirc_multiple_reattaches_all_resolve_no_row_double_counted():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    run_1_rows = [e for e in payload["events"] if e["request_id"] in ("rid-run-1", "rid-reattach-1a", "rid-reattach-1b")]
    # Exactly the dispatch plus its two reattaches — no duplicates, no
    # extras, and none of them collapsed into each other.
    assert len(run_1_rows) == 3
    assert all(r["outcome"] == {"state": "succeeded", "detail": "run_complete"} for r in run_1_rows)
    # The join record itself is still never its own row.
    assert not any(e["request_id"] == "rid-run-1-watch" for e in payload["events"])


def test_gate_round_6_lkirc_a_sync_already_active_deploy_receives_the_same_terminal_outcome_as_the_original():
    # lkirc, round 6: the SAME defect as round 5, at the sync
    # already-active path instead of the async reattach path — main.py's
    # _track_sync_reattach returns the SAME existing op, but the audit row
    # used to carry no link to it at all.
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    original = next(e for e in payload["events"] if e["request_id"] == "rid-run-3")
    active_1 = next(e for e in payload["events"] if e["request_id"] == "rid-active-3a")
    active_2 = next(e for e in payload["events"] if e["request_id"] == "rid-active-3b")
    expected = {"state": "succeeded", "detail": "run_complete"}
    assert original["outcome"] == expected
    assert active_1["outcome"] == expected
    assert active_2["outcome"] == expected


def test_gate_round_6_lkirc_a_sync_already_active_teardown_receives_the_same_terminal_outcome_as_the_original():
    # Same fix, the other action class — do not fix one and leave the
    # other (both explicitly named in the review).
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    original = next(e for e in payload["events"] if e["request_id"] == "rid-run-4")
    active = next(e for e in payload["events"] if e["request_id"] == "rid-active-4a")
    assert original["outcome"]["state"] == "failed"
    assert active["outcome"] == original["outcome"]


def test_gate_round_6_lkirc_repeated_sync_reattaches_all_resolve_no_row_double_counted():
    # lkirc asked for this explicitly: REPEATED sync reattaches (not just
    # one) on a single run all resolve to that run's single terminal
    # outcome, and none of them collapse into or duplicate each other.
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    run_3_rows = [e for e in payload["events"] if e["request_id"] in ("rid-run-3", "rid-active-3a", "rid-active-3b")]
    assert len(run_3_rows) == 3
    assert all(r["outcome"] == {"state": "succeeded", "detail": "run_complete"} for r in run_3_rows)
    assert not any(e["request_id"] == "rid-run-3-watch" for e in payload["events"])


# ----------------------------------------------------------------------
# Outcome rendering (AC 2 / AC 2a).
# ----------------------------------------------------------------------

def test_a_refusal_overrides_watched_acceptance_and_never_leaks_raw_at_default():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-deploy-2")
    assert row["outcome"]["state"] == "failed"
    assert row["outcome"]["detail"] == "facility-busy"
    assert "facility-busy" not in row["outcome"]["headline"]


def test_switch_source_carries_a_real_terminal_verdict():
    client = _client(VIEWER_IN_MEDIA_ENGINEERS)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-switch-1")
    assert row["outcome"]["state"] == "succeeded"


def test_a_watched_action_in_flight_never_carries_headline_meaning_next_step():
    # in-flight is acceptance-only — it must not smuggle a verdict-shaped
    # payload in through the failure fields.
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-deploy-1")
    assert row["outcome"] == {"state": "in_flight", "detail": "dispatched"}


def test_a_row_with_an_unrecoverable_outcome_renders_unknown_end_to_end():
    # codex R496-C P1-2, through the full pipeline: DEPLOY_BLANK_OUTCOME is
    # a fully well-formed fmt=2 line whose `outcome` value happens to be
    # blank. The row still renders (gated normally, real actor/action/
    # target), and its outcome is an honest "unknown" — never a forged
    # "failed", never "in flight".
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    row = next(e for e in payload["events"] if e["request_id"] == "rid-deploy-corrupted")
    assert row["actor"] == "erin"
    assert row["target"] == "wl-c"
    assert row["outcome"]["state"] == "unknown"
    assert row["outcome"]["detail"] == ""
    # The headline is what's most likely to be read alone — it must not
    # assert a verdict either way (the meaning is free to name "failed" as
    # one of several honest possibilities; that's accurate, not the bug).
    assert row["outcome"]["headline"] == "Outcome unknown"


# ----------------------------------------------------------------------
# AC 7 — an outage renders differently from an empty history.
# ----------------------------------------------------------------------

def test_loki_unreachable_is_a_distinct_reason_from_a_genuine_empty_history(monkeypatch):
    def _boom(**kwargs):
        raise audit_events.loki.LokiAPIError(0, "connection refused")

    monkeypatch.setattr(audit_events.loki, "query_range", _boom)
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["reason"] == "loki-unreachable"
    assert payload["events"] == []


def test_a_genuinely_empty_history_reads_ok_not_unreachable(monkeypatch):
    monkeypatch.setattr(audit_events.loki, "query_range", lambda **kwargs: [])
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["reason"] == ""
    assert payload["events"] == []


def test_loki_unconfigured_is_its_own_reason_and_makes_no_loki_call(monkeypatch):
    def _fail(**kwargs):
        raise AssertionError("must not call Loki when unconfigured")

    monkeypatch.setattr(audit_events.loki, "query_range", _fail)
    monkeypatch.setattr(audit_events.loki, "raw_runtime_config", _fail)
    client = _client(OPERATOR_ONLY, loki_configured=False)
    payload = client.get("/api/audit/events").json()
    assert payload["reason"] == "loki-unconfigured"
    assert payload["events"] == []


def test_unauthenticated_request_is_401_and_never_calls_loki(monkeypatch):
    def _fail(**kwargs):
        raise AssertionError("must not call Loki for an unauthenticated request")

    monkeypatch.setattr(audit_events.loki, "query_range", _fail)
    settings = Settings(runtime_mode="local", dev_login_enabled=True, loki=LokiSettings(url="http://loki.test"))
    client = TestClient(create_app(settings=settings))
    # deliberately no /auth/login — no session established
    resp = client.get("/api/audit/events")
    assert resp.status_code == 401


# ----------------------------------------------------------------------
# Window (conditions 1/2/3): known when derivable, unknown otherwise, never
# a hardcoded fallback.
# ----------------------------------------------------------------------

def test_window_known_from_the_global_when_no_stream_selector_matches():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["window"]["known"] is True
    assert payload["window"]["seconds"] == 168 * 3600


def test_window_uses_a_matching_stream_selector_over_the_global(monkeypatch):
    monkeypatch.setattr(
        audit_events.loki, "raw_runtime_config",
        lambda **kwargs: (
            "compactor:\n  retention_enabled: true\n"
            "limits_config:\n  retention_period: 168h\n  retention_stream:\n"
            '    - selector: \'{job="dmf-cms/dmf-cms"}\'\n      period: 720h\n      priority: 1\n'
        ),
    )
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["window"]["seconds"] == 720 * 3600


def test_window_unknown_when_retention_not_enforced(monkeypatch):
    monkeypatch.setattr(
        audit_events.loki, "raw_runtime_config",
        lambda **kwargs: "compactor:\n  retention_enabled: false\nlimits_config:\n  retention_period: 168h\n",
    )
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["window"]["known"] is False
    assert payload["window"]["seconds"] is None
    # window unavailability doesn't blank the lane -- events are still real
    assert payload["reason"] == ""


def test_window_unknown_when_config_endpoint_unavailable(monkeypatch):
    def _boom(**kwargs):
        raise audit_events.loki.LokiAPIError(404, "not found")

    monkeypatch.setattr(audit_events.loki, "raw_runtime_config", _boom)
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["window"]["known"] is False
    assert payload["reason"] == ""  # query_range still succeeded independently


# ----------------------------------------------------------------------
# F6 — a bound that binds must be disclosed.
# ----------------------------------------------------------------------

def test_not_capped_when_window_is_known_and_results_are_well_under_the_limit():
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["window"]["known"] is True
    assert payload["capped"] is False


def test_capped_when_the_window_could_not_be_derived(monkeypatch):
    # No derived retention window means the query actually ran against the
    # technical ceiling, not a real bound — the response must say so rather
    # than reading as an ordinary, complete history.
    monkeypatch.setattr(
        audit_events.loki, "raw_runtime_config",
        lambda **kwargs: "compactor:\n  retention_enabled: false\nlimits_config:\n  retention_period: 168h\n",
    )
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert payload["window"]["known"] is False
    assert payload["capped"] is True


def test_capped_when_the_result_count_hits_the_technical_limit(monkeypatch):
    # A saturated result count means Loki's own limit may have truncated
    # real rows before this function ever saw them.
    padded = FIXTURE_LINES + [DEPLOY] * (audit_events._MAX_RESULT_LINES - len(FIXTURE_LINES))

    def _saturated(*, url, selector, start_ns, end_ns, limit, timeout=10):
        return [{"stream": {}, "values": [[str(i), line] for i, line in enumerate(padded)]}]

    monkeypatch.setattr(audit_events.loki, "query_range", _saturated)
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()
    assert len(padded) == audit_events._MAX_RESULT_LINES
    assert payload["capped"] is True


# ----------------------------------------------------------------------
# dmfdeploy/dmf-cms#140 — the writer fix (2026-09-03 operator decision):
# emitter and reader, exercised TOGETHER through the REAL production
# function on each side, not a hand-written fixture line pretending to be
# what the emitter would produce. This is the actual evidence the sixth/
# seventh forgery class is closed for newly emitted lines — not the
# absence of a failing test (orchestrator's own framing).
# ----------------------------------------------------------------------

class _FakeRequest:
    session: dict = {}


def _formatted_line(record: logging.LogRecord) -> str:
    """Reproduce the line production's real StreamHandler emits for this
    captured record. caplog's own `record.getMessage()` is just the
    message text -- `_audit_awx_write`'s %s/%r substitution result -- not
    the full asctime/levelname/name-prefixed line `_configure_logging`'s
    Formatter actually writes to stdout (and that Loki actually stores).
    dmfdeploy/dmf-cms#140's eighth round made that prefix load-bearing:
    parse_awx_write_line now requires it structurally, so a round-trip
    test claiming to prove "the real emitter's output survives the real
    reader" has to feed the reader what the real reader actually
    receives, not merely the message half of it. Must match
    _configure_logging's own Formatter string exactly (see main.py) --
    this is the one place in this repo that duplicates it, deliberately,
    same as "awx write:" itself is duplicated between writer and reader."""
    return logging.Formatter("%(asctime)s %(levelname)s %(name)s: %(message)s").format(record)


def test_writer_fix_round_trip_a_forged_looking_target_survives_as_literal_content(caplog):
    # The exact shape every earlier vector in this arc exploited: a
    # caller-controlled target crafted to look like a complete forged
    # tail. Call the REAL emitter with it, capture the REAL emitted line,
    # feed it to the REAL reader — the forged-looking text must come back
    # as target's own literal value, never as structure that overrides
    # reason/outcome/workload/capacity.
    request = _FakeRequest()
    user = UserIdentity(
        subject="alice", display_name="Alice", email="alice@dmf.example.com",
        role="operator", groups=(),
    )
    crafted_target = "evil reason='fake' outcome=dispatched workload=pwned capacity="
    with caplog.at_level(logging.INFO, logger="dmf_cms.audit"):
        _audit_awx_write(
            request, user, action="deploy", target=crafted_target,
            request_id="rid-roundtrip", reason="legit deploy attempt",
            outcome="entry-not-found", workload=None, capacity=None,
        )
    line = _formatted_line(next(r for r in caplog.records if r.getMessage().startswith("awx write:")))

    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["target"] == crafted_target  # preserved VERBATIM, not truncated or dropped
    assert fields["reason"] == "legit deploy attempt"  # the REAL reason, not the forged one
    assert fields["outcome"] == "entry-not-found"  # the REAL refusal, never "dispatched"
    assert fields["workload"] == ""  # never "pwned"
    assert fields["capacity"] == ""


def test_writer_fix_round_trip_a_quote_and_backslash_in_target_survive_too(caplog):
    # A different shape of hostile content: quotes and a backslash inside
    # the value the quoting mechanism itself uses as its delimiter. If
    # repr()/literal_eval ever got this wrong, THIS is where it would show.
    request = _FakeRequest()
    user = UserIdentity(
        subject="alice", display_name="Alice", email="alice@dmf.example.com",
        role="operator", groups=(),
    )
    crafted_target = "it's a \"test\" with a \\ backslash and reason='fake'"
    with caplog.at_level(logging.INFO, logger="dmf_cms.audit"):
        _audit_awx_write(
            request, user, action="deploy", target=crafted_target,
            request_id="rid-roundtrip-2", reason="legit", outcome="entry-not-found",
            workload="wl'with quote", capacity='cap"with"doublequotes',
        )
    line = _formatted_line(next(r for r in caplog.records if r.getMessage().startswith("awx write:")))

    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["target"] == crafted_target
    assert fields["workload"] == "wl'with quote"
    assert fields["capacity"] == 'cap"with"doublequotes'
    assert fields["reason"] == "legit"
    assert fields["outcome"] == "entry-not-found"


def test_writer_fix_round_trip_blank_workload_and_capacity_never_render_as_the_word_none(caplog):
    # workload/capacity default to None in _audit_awx_write's own
    # signature -- %r on a bare None would print the literal text "None",
    # not an empty value. Confirms the `or ""` coercion at the call site
    # actually prevents that regression.
    request = _FakeRequest()
    user = UserIdentity(
        subject="alice", display_name="Alice", email="alice@dmf.example.com",
        role="operator", groups=(),
    )
    with caplog.at_level(logging.INFO, logger="dmf_cms.audit"):
        _audit_awx_write(
            request, user, action="teardown", target="wl-a",
            request_id="rid-roundtrip-3", reason="cleanup", outcome="dispatched",
            workload=None, capacity=None,
        )
    line = _formatted_line(next(r for r in caplog.records if r.getMessage().startswith("awx write:")))
    assert "None" not in line

    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["workload"] == ""
    assert fields["capacity"] == ""


def test_writer_fix_round_trip_a_reattach_carries_its_run_id_through_the_real_emitter(caplog):
    # gate round 5 (lkirc): _audit_awx_write's own new linked_request_id
    # parameter, through the REAL emitter -- not just the hand-built
    # fixture lines the other reattach tests use.
    request = _FakeRequest()
    user = UserIdentity(
        subject="grace", display_name="Grace", email="grace@dmf.example.com",
        role="operator", groups=(),
    )
    with caplog.at_level(logging.INFO, logger="dmf_cms.audit"):
        _audit_awx_write(
            request, user, action="deploy", target="wl-a",
            request_id="rid-reattach-real", reason="a real reattach", outcome="reattached",
            linked_request_id="rid-run-real",
        )
    line = _formatted_line(next(r for r in caplog.records if r.getMessage().startswith("awx write:")))
    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["request_id"] == "rid-reattach-real"
    assert fields["linked_request_id"] == "rid-run-real"


def test_writer_fix_omitting_linked_request_id_never_appends_the_trailing_field(caplog):
    # Every OTHER existing _audit_awx_write caller passes nothing for the
    # new parameter -- confirms the default genuinely omits the field
    # rather than appending e.g. "linked_request_id=None".
    request = _FakeRequest()
    user = UserIdentity(
        subject="alice", display_name="Alice", email="alice@dmf.example.com",
        role="operator", groups=(),
    )
    with caplog.at_level(logging.INFO, logger="dmf_cms.audit"):
        _audit_awx_write(
            request, user, action="deploy", target="wl-a",
            request_id="rid-ordinary", reason="an ordinary dispatch", outcome="dispatched",
        )
    line = _formatted_line(next(r for r in caplog.records if r.getMessage().startswith("awx write:")))
    assert "linked_request_id" not in line
    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["linked_request_id"] == ""


def test_gate_round_6_lkirc_the_missing_link_guard_fires_loudly_for_a_referencing_outcome_with_no_link(caplog):
    # gate round 6 (lkirc): "an audit row that describes an EXISTING
    # operation must carry that operation's identity" is now enforced
    # inside _audit_awx_write itself, not just remembered per call site —
    # this is what makes a THIRD omission impossible rather than merely
    # unlikely. Deliberately calling it wrong (a referencing outcome, no
    # link) to prove the guard actually fires.
    request = _FakeRequest()
    user = UserIdentity(
        subject="alice", display_name="Alice", email="alice@dmf.example.com",
        role="operator", groups=(),
    )
    with caplog.at_level(logging.ERROR, logger="dmf_cms.main"):
        _audit_awx_write(
            request, user, action="deploy", target="wl-a",
            request_id="rid-broken-caller", reason="a hypothetical future call site forgetting the link",
            outcome="reattached",
            # linked_request_id deliberately omitted
        )
    messages = [r.getMessage() for r in caplog.records]
    assert any("references an existing operation but was written with no linked_request_id" in m for m in messages)


def test_gate_round_6_lkirc_the_guard_never_raises_the_row_still_gets_written(caplog):
    # "Cannot take down an audit write in production": the guard logs, it
    # never raises -- a bug here must degrade the audit trail (the row
    # still gets written, unjoinable), never abort an already-successful
    # caller's own response.
    request = _FakeRequest()
    user = UserIdentity(
        subject="alice", display_name="Alice", email="alice@dmf.example.com",
        role="operator", groups=(),
    )
    with caplog.at_level(logging.INFO):
        _audit_awx_write(  # must not raise
            request, user, action="teardown", target="wl-b",
            request_id="rid-broken-caller-2", reason="same shape, teardown", outcome="already-active",
        )
    line = _formatted_line(next(r for r in caplog.records if r.getMessage().startswith("awx write:")))
    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["outcome"] == "already-active"
    assert fields["linked_request_id"] == ""  # degraded, but the row exists


def test_gate_round_6_lkirc_the_guard_never_fires_for_launch_rollback_or_finalise_purge(caplog):
    # Deliberate scope decision, not silence: these three actions emit the
    # SAME referencing tokens but have no terminal join to consume a link
    # this round (launch/verify-drain/rollback stay excluded-scope,
    # finalise-purge excluded-access — see audit_events.py's own COVERED
    # table) -- requiring a link nothing downstream ever reads would be
    # unenforceable ceremony, not a real fix, so the guard must never fire
    # for them regardless of what outcome they carry.
    request = _FakeRequest()
    user = UserIdentity(
        subject="alice", display_name="Alice", email="alice@dmf.example.com",
        role="operator", groups=(),
    )
    with caplog.at_level(logging.ERROR, logger="dmf_cms.main"):
        for action in ("launch", "rollback", "finalise-purge"):
            _audit_awx_write(
                request, user, action=action, target="wl-a",
                request_id=f"rid-{action}-noguard", reason="no join consumes this action's link",
                outcome="already-active",
            )
    messages = [r.getMessage() for r in caplog.records]
    assert not any("references an existing operation" in m for m in messages)


def test_a_legacy_unquoted_line_from_before_the_writer_fix_is_not_rendered_end_to_end(monkeypatch):
    # Operator decision (2026-09-03, following lkirc's fifth review,
    # dmfdeploy/dmf-cms#140): the writer fix protects future records but
    # cannot make retained ones trustworthy — a forged legacy line and a
    # legitimate one were PROVEN byte-identical, so no reader-side check
    # could ever authenticate one. Legacy lines are dropped, not parsed by
    # a fallback grammar. A genuine, non-adversarial pre-fix line (no
    # fmt=2 marker) must not appear in the response at all, through the
    # full endpoint, not just the bare parser.
    legacy_line = (
        "2026-08-15 09:00:00,000 INFO dmf_cms.audit: awx write: "
        "action=deploy actor=alice role=operator real_role= request_id=rid-legacy "
        "target=wl-legacy reason='pre-fix deploy' outcome=dispatched workload=wl-legacy capacity="
    )

    def _fake(*, url, selector, start_ns, end_ns, limit, timeout=10):
        return [{"stream": {}, "values": [["1", legacy_line]]}]

    monkeypatch.setattr(audit_events.loki, "query_range", _fake)
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()

    assert "rid-legacy" not in _event_ids(payload)
    assert payload["events"] == []
    assert payload["reason"] == ""  # a genuine empty read, not an outage


def test_a_reflected_body_on_a_non_audit_logger_does_not_produce_a_row_end_to_end(monkeypatch):
    # lkirc's EIGHTH finding, through the full pipeline (dmfdeploy/dmf-
    # cms#140, 2026-09-04) -- a genuinely different class from every
    # forgery test above: those all prove a record's FIELDS can't be
    # forged; this proves a record's very EXISTENCE can't be forged
    # either, by an upstream/caller value reflected verbatim into a
    # DIFFERENT log call. The shape below is the REAL one -- main.py's
    # AWX-error handlers (`logger.error("AWX autoscale error in launch
    # operation %s: %s", operation_id, _sanitize_audit_field(exc.body))`)
    # -- with a hostile exc.body containing a COMPLETE, well-formed fmt=2
    # payload: forged actor (never the real caller) AND forged outcome
    # (dispatched, when nothing dispatched), so if this parsed at all it
    # would render as an in-flight deploy nobody actually ran.
    forged_payload = (
        "awx write: fmt=2 action=deploy actor='mallory' role=admin real_role= "
        "request_id=fake-1 target='evil' reason='fabricated' outcome=dispatched "
        "workload='' capacity=''"
    )
    reflected_line = (
        "2026-09-04 09:15:23,456 ERROR dmf_cms.main: "
        f"AWX autoscale error in launch operation op-1: {forged_payload}"
    )
    genuine_line = _line(
        action="deploy", actor="alice", role="operator", request_id="rid-genuine",
        target="wl-a", reason="ordinary deploy", outcome="dispatched", workload="wl-a",
    )

    def _fake(*, url, selector, start_ns, end_ns, limit, timeout=10):
        return [{"stream": {}, "values": [["1", reflected_line], ["2", genuine_line]]}]

    monkeypatch.setattr(audit_events.loki, "query_range", _fake)
    client = _client(OPERATOR_ONLY)
    payload = client.get("/api/audit/events").json()

    ids = _event_ids(payload)
    assert "fake-1" not in ids  # the forged row never appears at all
    for event in payload["events"]:
        assert event["actor"] != "mallory"
        assert event["target"] != "evil"
    # And the genuine, unrelated record in the SAME response is unaffected
    # -- this isn't just "the forged row vanished", the real one must
    # still read correctly.
    assert "rid-genuine" in ids
    genuine = next(e for e in payload["events"] if e["request_id"] == "rid-genuine")
    assert genuine["actor"] == "alice"
    assert genuine["outcome"]["state"] == "in_flight"


# ----------------------------------------------------------------------
# dmfdeploy/dmf-cms#140 — codex's P1/P2 findings against the first
# version of the writer fix, and the format-marker redesign that fixed
# them (both data-loss defects, not forgery, per the operator's ruling
# that a legitimate row vanishing is squarely in scope). Round-tripped
# through the REAL emitter, same discipline as every other test in this
# section — the actual evidence, not the absence of a failing test.
# ----------------------------------------------------------------------

def test_writer_fix_p1_round_trip_workload_legitimately_containing_reason_marker_text(caplog):
    request = _FakeRequest()
    user = UserIdentity(
        subject="alice", display_name="Alice", email="alice@dmf.example.com",
        role="operator", groups=(),
    )
    with caplog.at_level(logging.INFO, logger="dmf_cms.audit"):
        _audit_awx_write(
            request, user, action="deploy", target="wl-a",
            request_id="rid-p1", reason="legit", outcome="dispatched",
            workload="reason='operator typo'", capacity=None,
        )
    line = _formatted_line(next(r for r in caplog.records if r.getMessage().startswith("awx write:")))

    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["workload"] == "reason='operator typo'"
    assert fields["reason"] == "legit"
    assert fields["outcome"] == "dispatched"


def test_writer_fix_p1_round_trip_capacity_legitimately_containing_reason_marker_text(caplog):
    request = _FakeRequest()
    user = UserIdentity(
        subject="alice", display_name="Alice", email="alice@dmf.example.com",
        role="operator", groups=(),
    )
    with caplog.at_level(logging.INFO, logger="dmf_cms.audit"):
        _audit_awx_write(
            request, user, action="deploy", target="wl-a",
            request_id="rid-p1b", reason="legit", outcome="dispatched",
            workload=None, capacity="reason='operator typo'",
        )
    line = _formatted_line(next(r for r in caplog.records if r.getMessage().startswith("awx write:")))

    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["capacity"] == "reason='operator typo'"
    assert fields["reason"] == "legit"


def test_writer_fix_round_trip_an_actor_forging_classification_fields_survives_as_literal_content(caplog):
    # actor is quoted as of this round specifically because it sits
    # BEFORE target in the classification scan -- through the REAL
    # emitter, a hostile subject claim must come back as target's own
    # literal actor value, never as forged role/real_role/request_id/
    # target structure.
    request = _FakeRequest()
    hostile_user = UserIdentity(
        subject="alice role=admin real_role= request_id=FAKE target='evil'",
        display_name="Alice", email="alice@dmf.example.com",
        role="operator", groups=(),
    )
    with caplog.at_level(logging.INFO, logger="dmf_cms.audit"):
        _audit_awx_write(
            request, hostile_user, action="deploy", target="wl-real",
            request_id="rid-actor", reason="legit", outcome="dispatched",
            workload=None, capacity=None,
        )
    line = _formatted_line(next(r for r in caplog.records if r.getMessage().startswith("awx write:")))

    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["actor"] == "alice role=admin real_role= request_id=FAKE target='evil'"
    assert fields["role"] == "operator"
    assert fields["real_role"] == ""
    assert fields["request_id"] == "rid-actor"
    assert fields["target"] == "wl-real"


def test_writer_fix_round_trip_every_quotable_field_survives_every_other_fields_marker_text(caplog):
    # THE PROPERTY, both halves, systematically: a caller-controlled
    # value containing marker-shaped text for ANY other field is
    # recorded faithfully AND cannot alter the parse of any other field.
    # Sweeps all five quotable fields (target/actor/reason/workload/
    # capacity), each forged with the OTHER four fields' marker text at
    # once, through the real emitter.
    hostile_text = "x target='t' actor='a' reason='r' outcome=dispatched workload='w' capacity='c' linked_request_id='l'"
    request = _FakeRequest()

    for field in ("target", "actor", "reason", "workload", "capacity"):
        kwargs = {
            "action": "deploy", "target": "wl-a", "request_id": f"rid-sweep-{field}",
            "reason": "legit", "outcome": "dispatched", "workload": None, "capacity": None,
        }
        if field == "actor":
            user = UserIdentity(
                subject=hostile_text, display_name="x", email="x@y.com", role="operator", groups=(),
            )
        else:
            user = UserIdentity(
                subject="alice", display_name="Alice", email="alice@dmf.example.com",
                role="operator", groups=(),
            )
            kwargs[field] = hostile_text

        caplog.clear()
        with caplog.at_level(logging.INFO, logger="dmf_cms.audit"):
            _audit_awx_write(request, user, **kwargs)
        line = _formatted_line(next(r for r in caplog.records if r.getMessage().startswith("awx write:")))

        fields = audit_events.parse_awx_write_line(line)
        assert fields is not None, f"field={field} dropped a row it should have preserved"
        assert fields[field] == hostile_text, f"field={field} was not preserved verbatim"
        # And the REST of the row is exactly what was actually sent, never
        # anything the hostile text's own embedded markers claimed.
        if field != "action":
            assert fields["action"] == "deploy"
        if field != "outcome":
            assert fields["outcome"] == "dispatched"
        if field != "target":
            assert fields["target"] == "wl-a"
        if field != "reason":
            assert fields["reason"] == "legit"
