"""Unit tests for the pure functions behind dmfdeploy/dmfdeploy#496's
Activity History lane — line parsing, retention-window derivation, class
membership/gating, and outcome/disclosure mapping. No FastAPI, no Loki I/O:
every fixture here is a literal string, never generated by calling the code
under test (plan §7 AC 5a's tautology ban applies to these building blocks
too, not just the endpoint-level fixture).
"""

from __future__ import annotations

import dmf_cms.audit_events as audit_events


# The fixed shape _configure_logging's own Formatter produces
# (main.py: "%(asctime)s %(levelname)s %(name)s: %(message)s") — the
# reader now requires this structurally, by position, before it will
# even look at "awx write:" (dmfdeploy/dmf-cms#140, eighth round,
# provenance). "dmf_cms.audit" is the real name `audit_logger` carries in
# production; a handful of tests below deliberately use a DIFFERENT name
# or omit this prefix entirely to prove the provenance check itself.
_LOG_LINE_PREFIX = "2026-09-04 09:15:23,456 INFO dmf_cms.audit: "


def _new_line(
    *, action="deploy", actor="alice", role="operator", real_role="", request_id="rid-1",
    target="wl-a", reason="demo", outcome="dispatched", workload="", capacity="",
    linked_request_id=None, marker_prefix="awx write: fmt=2 ", log_prefix=_LOG_LINE_PREFIX,
) -> str:
    """Build a REALISTIC line for unit tests below: `log_prefix` (default:
    a genuine `dmf_cms.audit` logging prefix) followed by the fmt=2
    grammar (dmfdeploy/dmf-cms#140) — target/actor/reason/workload/
    capacity quoted, exactly as the real emitter writes them; action/
    role/real_role/request_id/outcome plain. Both prefixes are
    overridable: `log_prefix` for the handful of tests exercising the
    provenance check directly (wrong logger name, or no logging prefix at
    all), `marker_prefix` for the handful exercising a malformed/absent
    `fmt=` marker."""
    line = (
        f"{marker_prefix}action={action} actor={actor!r} role={role} real_role={real_role} "
        f"request_id={request_id} target={target!r} reason={reason!r} "
        f"outcome={outcome} workload={workload!r} capacity={capacity!r}"
    )
    if linked_request_id is not None:
        line += f" linked_request_id={linked_request_id}"
    return log_prefix + line


# ----------------------------------------------------------------------
# parse_awx_write_line
# ----------------------------------------------------------------------

def test_parses_a_plain_line_with_logging_prefix():
    line = _new_line(
        request_id="rid-1", target="wl-a", reason="demo deploy", outcome="dispatched", workload="wl-a",
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields == {
        "action": "deploy",
        "actor": "alice",
        "role": "operator",
        "real_role": "",
        "request_id": "rid-1",
        "target": "wl-a",
        "reason": "demo deploy",
        "outcome": "dispatched",
        "workload": "wl-a",
        "capacity": "",
        "linked_request_id": "",
    }


def test_parses_the_auto_rollback_trailing_field():
    # Auto-rollback's own dispatch is on audit_logger too as of
    # dmfdeploy/dmf-cms#140's eighth round -- the default log_prefix
    # (dmf_cms.audit) is the real shape this line carries in production.
    line = _new_line(
        action="rollback", actor="system:auto-rollback", role="system", request_id="rid-child",
        target="run-123", reason="auto: deploy wl-a failed", outcome="auto-triggered",
        linked_request_id="rid-parent",
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields["linked_request_id"] == "rid-parent"
    assert fields["target"] == "run-123"
    assert fields["workload"] == ""


def test_reason_containing_the_next_markers_own_text_does_not_corrupt_parsing():
    # The trap named in the plan §4.1/§4.2: reason is a Python repr and may
    # legitimately contain " outcome=" as ordinary text. A parser that
    # anchors on the NEXT bare marker instead of quote-scanning reason
    # would truncate it here.
    line = _new_line(
        action="teardown", request_id="rid-2", target="wl-b",
        reason="fixing outcome=broken thing, ok?", outcome="dispatched",
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields["reason"] == "fixing outcome=broken thing, ok?"
    assert fields["outcome"] == "dispatched"


def test_reason_with_escaped_quote_round_trips():
    # A string containing BOTH ' and " forces Python's repr() to pick
    # single-quote delimiters and escape the internal single quote as
    # \' -- exercising _scan_repr_string_end's own escape handling
    # (the `if c == "\\": i += 2` branch), not just a quote Python's
    # repr() can sidestep by choosing the other delimiter.
    reason = 'it\'s a "test"'
    assert repr(reason).startswith("'") and "\\'" in repr(reason)  # confirms the fixture is real
    line = _new_line(request_id="rid-3", target="wl-a", reason=reason, outcome="dispatched")
    fields = audit_events.parse_awx_write_line(line)
    assert fields["reason"] == reason


def test_missing_awx_write_prefix_returns_none():
    assert audit_events.parse_awx_write_line("some unrelated log line") is None


def test_missing_field_returns_none():
    # fmt=2 present but target/reason/... never arrive — the row is
    # dropped just like any other violation of the grammar's contract.
    # (Realistic log_prefix so this fails for the field's OWN reason, not
    # incidentally for lacking one -- dmfdeploy/dmf-cms#140 eighth round.)
    line = _LOG_LINE_PREFIX + "awx write: fmt=2 action=deploy actor='alice' role=operator real_role= request_id=rid-1"
    assert audit_events.parse_awx_write_line(line) is None


def test_reason_and_everything_before_it_missing_still_fails_to_parse():
    # A DIFFERENT failure: `reason=` itself is never found at all — there
    # is nothing for _require_quoted_field to anchor against, so the row
    # is dropped even though target parsed fine.
    line = (
        _LOG_LINE_PREFIX
        + "awx write: fmt=2 action=deploy actor='alice' role=operator real_role= request_id=rid-1 target='wl-a'"
    )
    assert audit_events.parse_awx_write_line(line) is None


def test_a_malformed_reason_on_the_new_format_drops_the_row_entirely():
    # dmfdeploy/dmf-cms#140 (operator decision, 2026-09-03): unlike the
    # deleted legacy grammar's tolerant "enrichment failure" fallback, the
    # fmt=2 contract REQUIRES every quotable field to be well-formed —
    # there is no partial admission left to test. An unterminated reason
    # quote is a hard classification failure (AC 5b): the whole row is
    # dropped, not retained with blank/forged fields.
    line = (
        _LOG_LINE_PREFIX
        + "awx write: fmt=2 action=deploy actor='alice' role=operator real_role= "
        "request_id=rid-1 target='wl-a' reason='never closes, no matching quote anywhere in the rest of this line"
    )
    assert audit_events.parse_awx_write_line(line) is None


def test_forgery_resistance_cannot_attribute_the_row_to_a_different_actor():
    # actor is parsed strictly BEFORE target/reason and never re-derived
    # from anything after it — a reason that LOOKS like it's trying to
    # name a different actor has zero effect, because reason's own
    # (well-formed, quoted) value is just data by the time it's read.
    line = _new_line(
        actor="alice", request_id="rid-real", target="wl-a",
        reason="forged actor=mallory role=admin outcome=dispatched",
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["actor"] == "alice"
    assert fields["reason"] == "forged actor=mallory role=admin outcome=dispatched"
    assert fields["role"] == "operator"
    assert fields["outcome"] == "dispatched"  # the REAL, plain outcome= marker, never a forged one


# ----------------------------------------------------------------------
# dmf-cms#140 (lkirc/codex, across many review rounds) — forgery
# resistance on the fmt=2 grammar. The per-field boundary-GUESSING
# mechanism this section used to regression-test (duplicate-marker
# ambiguity checks, glued-marker detection, legacy quote-vs-plain
# discrimination, second-reason-candidate discrimination) is gone along
# with the legacy parser it existed to protect (operator decision,
# 2026-09-03: see the module STATUS NOTE) — deleted, not left dormant.
# On fmt=2, actor/target/reason/workload/capacity are each independently
# quote-bound by `_require_quoted_field`: a field's content, whatever it
# contains, can never be mistaken for a later field's marker, because no
# boundary is ever inferred from searching the value's own text. What
# remains here is what still applies to that grammar: the trailing-field
# consistency check, and proof that ordinary marker-shaped text inside a
# quoted field's own value survives as literal content (the rest of that
# proof lives in the P1 tests just below).
# ----------------------------------------------------------------------

def test_property_a_genuine_auto_rollback_linked_request_id_still_parses():
    # The trailing `linked_request_id` field is still consistency-checked
    # against the row's own action/actor (_parse_new_format_line's own
    # final check) -- a genuine auto-rollback row carrying it must parse
    # normally.
    line = _new_line(
        action="rollback", actor="system:auto-rollback", role="system",
        request_id="rid-child", target="run-123", reason="auto: deploy wl-a failed",
        outcome="auto-triggered", workload="", capacity="",
        linked_request_id="rid-parent",
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["linked_request_id"] == "rid-parent"


def test_property_a_legitimate_reason_mentioning_marker_like_text_still_parses():
    # Regression guard carried forward from the legacy-era version of this
    # test: an honest reason that happens to mention marker-shaped text in
    # ordinary prose (e.g. "role=" as a genuine word an operator typed)
    # must still parse -- on fmt=2 this holds unconditionally, because
    # reason's value is quote-scanned, never boundary-guessed from its
    # own content.
    line = _new_line(
        reason="confirmed with role=lead engineer, target=wl-a is correct",
        outcome="dispatched", workload="wl-a",
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["reason"] == "confirmed with role=lead engineer, target=wl-a is correct"
    assert fields["outcome"] == "dispatched"


# ----------------------------------------------------------------------
# dmfdeploy/dmf-cms#140 — the format-marker dispatch (codex's
# eighth-round finding): the reader stops GUESSING per field which
# grammar a line uses and dispatches on an explicit `fmt=2` marker
# instead. codex's P1 finding (a genuinely new-format quoted field
# legitimately containing marker-shaped text) is pinned directly below.
# codex's companion P2 finding was about the now-deleted legacy grammar
# and was retired along with it (operator decision, 2026-09-03).
# ----------------------------------------------------------------------

def test_dmf_cms_140_p1_a_new_format_quoted_workload_containing_reason_marker_text_parses():
    # codex P1: a genuinely NEW-format, properly quoted workload whose
    # own value legitimately contains "reason='...'" text used to trip
    # the legacy reason-ambiguity check, which had no way to know it was
    # looking inside an already-safely-bounded quoted span. Under the
    # fmt=2 grammar this check never runs at all -- target is
    # independently quote-bound, so nothing upstream of reason can
    # inject a competing candidate, and the row must parse cleanly.
    line = (
        _LOG_LINE_PREFIX
        + "awx write: fmt=2 action=deploy actor='alice' role=operator real_role= "
        "request_id=rid-p1 target='wl-a' reason='legit' outcome=dispatched "
        "workload=\"reason='operator typo'\" capacity=''"
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["workload"] == "reason='operator typo'"
    assert fields["reason"] == "legit"
    assert fields["outcome"] == "dispatched"


def test_dmf_cms_140_p1_a_new_format_quoted_capacity_containing_reason_marker_text_parses():
    # Same property, capacity instead of workload.
    line = (
        _LOG_LINE_PREFIX
        + "awx write: fmt=2 action=deploy actor='alice' role=operator real_role= "
        "request_id=rid-p1b target='wl-a' reason='legit' outcome=dispatched "
        "workload='' capacity=\"reason='operator typo'\""
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["capacity"] == "reason='operator typo'"
    assert fields["reason"] == "legit"


def test_an_unrecognised_fmt_version_fails_closed_rather_than_guessing():
    # A future format this code doesn't know about yet must not be
    # silently treated as fmt=2 (which could misread its own shape) --
    # there is exactly one way to be accepted, so anything else, known or
    # not, is rejected identically to a line with no marker at all.
    line = (
        _LOG_LINE_PREFIX
        + "awx write: fmt=99 action=deploy actor='alice' role=operator real_role= "
        "request_id=rid-future target='wl-a' reason='x' outcome=dispatched workload='' capacity=''"
    )
    assert audit_events.parse_awx_write_line(line) is None


def test_property_an_actor_forging_classification_fields_cannot_alter_the_parse_on_the_new_format():
    # actor is quoted as of this round specifically because it is parsed
    # BEFORE target in the classification scan -- on the fmt=2 grammar it
    # must be independently quote-bound just like target, or a hostile
    # actor value could inject fake role=/real_role=/request_id=/target=
    # markers that get found FIRST, upstream of everything the writer fix
    # otherwise proves.
    line = (
        _LOG_LINE_PREFIX
        + "awx write: fmt=2 action=deploy actor=\"alice role=admin real_role= request_id=FAKE target='evil'\" "
        "role=operator real_role= request_id=rid-real target='wl-real' reason='legit' "
        "outcome=dispatched workload='' capacity=''"
    )
    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["actor"] == "alice role=admin real_role= request_id=FAKE target='evil'"
    assert fields["role"] == "operator"  # the REAL role, never "admin"
    assert fields["real_role"] == ""
    assert fields["request_id"] == "rid-real"  # never "FAKE"
    assert fields["target"] == "wl-real"  # never "evil"


# ----------------------------------------------------------------------
# dmfdeploy/dmf-cms#140, EIGHTH round (lkirc, 2026-09-04) — PROVENANCE, a
# different mechanism from everything above. Every test above proves a
# genuine record's FIELDS can't be forged; none of them say anything
# about whether a "record" came from the writer at all. main.py's AWX-
# error handlers log upstream exc.body content (_sanitize_audit_field-
# escaped for CR/LF only, never for this) on the plain module logger --
# a well-formed `awx write: fmt=2 ...` payload reflected verbatim into
# one of those messages used to become a fully parseable, fabricated row,
# because the old dispatch (`line.find("awx write:")`) searched the
# WHOLE line for the marker regardless of which logger emitted it.
#
# Fixed with a mechanism the field-boundary fixes above could never be:
# PROVENANCE. Logger identity is a property of which CODE PATH emitted a
# record, never of any value that code path's message happens to
# contain, so no caller/upstream content can forge it -- unlike quoting
# or a longer marker string, which are still content the attacker
# controls. `_new_line()`'s default `log_prefix` already exercises the
# genuine-record half of this property throughout this whole file (every
# test above parses successfully BECAUSE it carries a real
# `dmf_cms.audit` prefix); the tests below isolate the OTHER half.
# ----------------------------------------------------------------------

def test_a_reflected_body_with_a_forged_actor_and_outcome_produces_no_row():
    # The exact shape lkirc reported: an upstream error body containing a
    # COMPLETE, well-formed fmt=2 payload -- forged actor AND forged
    # outcome, so if this ever parsed, it would read as a real dispatch
    # by "mallory" rather than the refusal it actually was -- reflected
    # into a DIFFERENT log call's message on the plain module logger, the
    # same shape main.py's AWX-error handlers actually emit.
    forged_payload = (
        "awx write: fmt=2 action=deploy actor='mallory' role=admin real_role= "
        "request_id=fake-1 target='evil' reason='fabricated' outcome=dispatched "
        "workload='' capacity=''"
    )
    line = (
        "2026-09-04 09:15:23,456 ERROR dmf_cms.main: "
        f"AWX autoscale error in launch operation op-1: {forged_payload}"
    )
    assert audit_events.parse_awx_write_line(line) is None


def test_the_identical_payload_on_the_real_audit_logger_does_parse():
    # Control, isolating what actually changed: the EXACT SAME fmt=2
    # payload as above, unaltered, on the genuine dmf_cms.audit logger,
    # as its message's own first content (no upstream-error prose ahead
    # of it) -- must parse cleanly, with the actor/outcome the payload
    # actually names. Proves the row above was dropped for provenance,
    # not because that particular payload was somehow malformed.
    forged_payload = (
        "awx write: fmt=2 action=deploy actor='mallory' role=admin real_role= "
        "request_id=fake-1 target='evil' reason='fabricated' outcome=dispatched "
        "workload='' capacity=''"
    )
    line = "2026-09-04 09:15:23,456 ERROR dmf_cms.audit: " + forged_payload
    fields = audit_events.parse_awx_write_line(line)
    assert fields is not None
    assert fields["actor"] == "mallory"
    assert fields["outcome"] == "dispatched"


def test_a_genuine_logger_but_the_marker_is_not_the_first_thing_in_the_message_produces_no_row():
    # The OTHER half of the check, isolated: even ON the real audit
    # logger, a message that puts anything ahead of "awx write:" fails --
    # audit_logger is used for nothing else today, but this is what
    # keeps that true structurally rather than by convention alone, and
    # is what a future hypothetical audit_logger.info("some prefix: awx
    # write: ...") call would need to avoid.
    line = "2026-09-04 09:15:23,456 INFO dmf_cms.audit: note: " + _new_line(log_prefix="")
    assert audit_events.parse_awx_write_line(line) is None


def test_a_logger_name_that_merely_resembles_dmf_cms_audit_produces_no_row():
    # Exact match, not prefix/substring match -- a name that LOOKS close
    # (an extra character, a typo) must not be treated as the real thing.
    for near_miss in ("dmf_cms.audit2", "dmf_cms.audits", "xdmf_cms.audit", "dmf_cms.Audit"):
        line = f"2026-09-04 09:15:23,456 INFO {near_miss}: " + _new_line(log_prefix="")
        assert audit_events.parse_awx_write_line(line) is None, near_miss


# ----------------------------------------------------------------------
# resolve_retention_window
# ----------------------------------------------------------------------

_LABELS = {"namespace": "dmf-cms", "job": "dmf-cms/dmf-cms"}


def test_retention_not_enforced_when_compactor_disabled():
    config = """
compactor:
  retention_enabled: false
limits_config:
  retention_period: 168h
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.known is False
    assert window.reason == "not-enforced"


def test_retention_falls_back_to_global_when_no_stream_selector_matches():
    # This is condition 1's exact case: the queried job label matches
    # neither the k3s-audit nor the security-job stream rule, so today the
    # global is correct -- but the code must evaluate that, not assume it.
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
  retention_stream:
    - selector: '{job="k3s-audit"}'
      period: 720h
      priority: 2
    - selector: '{job=~".+-security"}'
      period: 720h
      priority: 1
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.known is True
    assert window.seconds == 168 * 3600
    assert window.reason == ""


def test_retention_uses_matching_stream_selector_over_global():
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
  retention_stream:
    - selector: '{job="dmf-cms/dmf-cms"}'
      period: 720h
      priority: 1
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.known is True
    assert window.seconds == 720 * 3600


def test_retention_stream_priority_breaks_a_tie_between_two_matching_rules():
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
  retention_stream:
    - selector: '{job=~"dmf-cms.*"}'
      period: 240h
      priority: 1
    - selector: '{job="dmf-cms/dmf-cms"}'
      period: 480h
      priority: 5
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.seconds == 480 * 3600


def test_retention_equal_priority_tie_takes_the_shorter_period():
    # codex R496-A F2a: Loki resolves an equal-priority tie by taking the
    # SHORTER period, not whichever rule this code happened to encounter
    # first in the list. Rule order below is deliberately the OPPOSITE of
    # the expected answer (720h listed first) so a "first encountered"
    # bug would report the wrong, longer window.
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
  retention_stream:
    - selector: '{job="dmf-cms/dmf-cms"}'
      period: 720h
      priority: 3
    - selector: '{job=~"dmf-cms.*"}'
      period: 240h
      priority: 3
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.seconds == 240 * 3600


def test_retention_selector_missing_label_treated_as_empty_string():
    # codex R496-A F2b: Prometheus/Loki matcher semantics treat an absent
    # label as present-with-value-"" — so a negative matcher on a label the
    # query never carries legitimately MATCHES. _LABELS has no "container"
    # key at all; the old (buggy) behaviour treated a missing label as an
    # automatic non-match, silently falling through to the (longer) global.
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
  retention_stream:
    - selector: '{job="dmf-cms/dmf-cms", container!="foo"}'
      period: 24h
      priority: 1
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.seconds == 24 * 3600


def test_retention_selector_positive_missing_label_match_does_not_match():
    # Same semantics, opposite polarity: a POSITIVE matcher on an absent
    # label only matches an explicit empty string, never silently.
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
  retention_stream:
    - selector: '{job="dmf-cms/dmf-cms", container="foo"}'
      period: 24h
      priority: 1
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.seconds == 168 * 3600  # the stream rule never matched; falls to global


def test_retention_unavailable_on_unparseable_yaml():
    window = audit_events.resolve_retention_window("not: valid: yaml: [", _LABELS)
    assert window.known is False
    assert window.reason == "unparseable"


def test_retention_unparseable_on_garbage_duration():
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: not-a-duration
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.known is False
    assert window.reason == "unparseable"


def test_retention_unparseable_when_limits_config_missing():
    config = "compactor:\n  retention_enabled: true\n"
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.known is False
    assert window.reason == "unparseable"


def test_retention_a_broken_regex_selector_never_matches_and_never_crashes():
    config = """
compactor:
  retention_enabled: true
limits_config:
  retention_period: 168h
  retention_stream:
    - selector: '{job=~"("}'
      period: 720h
      priority: 9
"""
    window = audit_events.resolve_retention_window(config, _LABELS)
    assert window.known is True
    assert window.seconds == 168 * 3600  # falls back to global, does not crash


# ----------------------------------------------------------------------
# classify_record / user_passes_gate — the closed membership table
# ----------------------------------------------------------------------

def test_classify_covered_classes():
    assert audit_events.classify_record("deploy", "alice") == "deploy"
    assert audit_events.classify_record("teardown", "alice") == "teardown"
    assert audit_events.classify_record("switch-source", "bob") == "switch-source"


def test_classify_splits_rollback_by_actor():
    assert audit_events.classify_record("rollback", "system:auto-rollback") == "auto-rollback"
    assert audit_events.classify_record("rollback", "alice") == "rollback"


def test_classify_excluded_classes_are_named_not_dropped_from_the_table():
    for action in ("finalise-purge", "launch", "verify-drain"):
        cls = audit_events.classify_record(action, "alice")
        assert cls == action
        assert audit_events._CLASS_INFO[cls]["status"] != audit_events.COVERED


def test_classify_unrecognised_action_fails_closed():
    assert audit_events.classify_record("mystery-action", "alice") is None


def test_gate_operator_role_passes_operator_classes_not_media_workloads():
    assert audit_events.user_passes_gate("deploy", role="operator", groups=()) is True
    assert audit_events.user_passes_gate("teardown", role="operator", groups=()) is True
    assert audit_events.user_passes_gate("auto-rollback", role="operator", groups=()) is True
    assert audit_events.user_passes_gate("switch-source", role="operator", groups=()) is False


def test_gate_viewer_in_media_engineers_passes_only_switch_source():
    groups = ("dmf-console-viewer", "media-engineers")
    assert audit_events.user_passes_gate("switch-source", role="viewer", groups=groups) is True
    assert audit_events.user_passes_gate("deploy", role="viewer", groups=groups) is False


def test_gate_excluded_classes_pass_for_nobody():
    for cls in ("finalise-purge", "launch", "verify-drain", "rollback"):
        assert audit_events.user_passes_gate(cls, role="admin", groups=("media-engineers",)) is False


# ----------------------------------------------------------------------
# outcome / disclosure mapping
# ----------------------------------------------------------------------

def test_a_blank_outcome_is_unknown_not_failed_for_every_watched_action():
    # codex R496-C P1-2: the property this test is named for. A blank
    # outcome means the record's outcome field was lost (unrecoverable),
    # not that the action failed — rendering it as a definite failure
    # would be this lane claiming knowledge it does not have, the same
    # defect the whole round exists to remove, opposite sign. Covers
    # every action resolve_outcome_state actually branches on, including
    # switch-source (which has its own separate "== active" check that
    # must not see a blank outcome fall through to its else-failed arm).
    for action in ("deploy", "teardown", "rollback", "finalise-purge", "switch-source"):
        assert audit_events.resolve_outcome_state(action, "") == "unknown"


def test_a_blank_outcome_is_unknown_even_though_blank_is_never_a_real_refusal_token():
    # Distinguishes the new THIRD case from the unenumerated-refusal rule
    # (F3) it must never be folded into: a REAL, non-blank, never-seen
    # token still correctly renders failed (re-confirming F3 is
    # untouched), while blank specifically renders unknown — proving
    # "unknown" is not just another way of writing "unenumerated".
    assert audit_events.resolve_outcome_state("deploy", "some-token-nobody-catalogued") == "failed"
    assert audit_events.resolve_outcome_state("deploy", "") == "unknown"


def test_build_outcome_unknown_state_never_asserts_a_definite_verdict():
    result = audit_events.build_outcome("deploy", "")
    assert result["state"] == "unknown"
    # The headline is the one line most likely to be read alone — it must
    # not claim a verdict either way. The meaning is free to name "failed"
    # as one of several honest POSSIBILITIES (that's the accurate
    # statement); the bug this guards against is ASSERTING it as fact.
    assert result["headline"] == "Outcome unknown"
    assert result["meaning"] == (
        "This action's outcome could not be read from the record — "
        "it may have succeeded, failed, or still be in progress."
    )


def test_watched_action_acceptance_outcome_is_in_flight():
    for action, outcome in (("deploy", "dispatched"), ("teardown", "launched"), ("rollback", "auto-triggered")):
        result = audit_events.build_outcome(action, outcome)
        assert result == {"state": "in_flight", "detail": outcome}


def test_reattach_shaped_acceptance_outcomes_are_also_in_flight():
    # "reattached" (get_or_create found an existing op, no new dispatch) and
    # "already-active" (the sync flow's own idempotency guard found an
    # in-flight AWX job) are both genuine in-flight realities reached via a
    # different code path than a fresh dispatch — main.py:4769, :4874 (and
    # the teardown/rollback siblings).
    for action in ("deploy", "teardown"):
        for outcome in ("reattached", "already-active"):
            assert audit_events.build_outcome(action, outcome)["state"] == "in_flight"
    assert audit_events.build_outcome("rollback", "already-in-progress")["state"] == "in_flight"


def test_already_active_other_run_is_a_refusal_not_an_acceptance():
    # codex R496-A F3's concrete proof case: rollback's identity-mismatch
    # branch (main.py:5315) never dispatches THIS run's rollback — a
    # DIFFERENT run's job was found active, and the request is refused
    # (409). Textually similar to "already-active" but semantically its
    # opposite; must render failed.
    result = audit_events.build_outcome("rollback", "already-active-other-run")
    assert result["state"] == "failed"


def test_an_unenumerated_refusal_token_is_terminal_not_in_flight():
    # codex R496-A F3: the fix must be allowlist-shaped, not "add the
    # missing tokens to a denylist" — main.py emits far more refusal
    # tokens than any denylist could enumerate (confirmation-mismatch,
    # conflict-active-job, entry-not-found, invalid-run-id, ... the list
    # keeps growing). A token this test has never seen before must STILL
    # render failed for a watched action, proving the acceptance set is
    # closed rather than the refusal set.
    for action in ("deploy", "teardown", "rollback", "finalise-purge"):
        result = audit_events.build_outcome(action, "some-refusal-token-invented-for-this-test")
        assert result["state"] == "failed"


def test_switch_source_active_is_a_real_succeeded_verdict():
    result = audit_events.build_outcome("switch-source", "active")
    assert result == {"state": "succeeded", "detail": "active"}


def test_switch_source_non_active_is_failed_with_generic_default_copy():
    result = audit_events.build_outcome("switch-source", "failed_rollback_required")
    assert result["state"] == "failed"
    assert result["detail"] == "failed_rollback_required"  # raw preserved, expert-only
    assert "failed_rollback_required" not in result["headline"]
    assert "failed_rollback_required" not in result["meaning"]


def test_refusal_token_overrides_watched_acceptance_and_gets_plain_language_copy():
    result = audit_events.build_outcome("deploy", "facility-busy")
    assert result["state"] == "failed"
    assert result["headline"] == "Another operation is already using this facility"
    assert result["detail"] == "facility-busy"  # raw string carried, never in headline/meaning/next_step
    for key in ("headline", "meaning", "next_step"):
        assert "facility-busy" not in result[key]


def test_awx_error_prefix_gets_generic_copy_and_keeps_raw_as_detail_only():
    result = audit_events.build_outcome("teardown", "awx-error:503")
    assert result["state"] == "failed"
    assert result["detail"] == "awx-error:503"
    for key in ("headline", "meaning", "next_step"):
        assert "awx-error:503" not in result[key]


def test_unrecognised_refusal_token_still_gets_honest_generic_copy_never_raw():
    # _describe_failure directly: the plan's refusal vocabulary (§4.4) is a
    # closed set, same principle as the class table — a token outside it
    # must still never leak raw at default, even with no specific copy
    # authored for it yet.
    copy = audit_events._describe_failure("some-new-refusal-nobody-mapped-yet")
    for key in ("headline", "meaning", "next_step"):
        assert "some-new-refusal-nobody-mapped-yet" not in copy[key]


def test_resolve_outcome_state_fails_safe_outside_the_known_vocabulary():
    # Defensive only: build_outcome is never called on an excluded row in
    # the real pipeline (list_audit_events drops those before reaching it),
    # but the function itself must not invent an in-flight/succeeded claim
    # for an action it does not recognise.
    assert audit_events.resolve_outcome_state("some-unknown-action", "whatever") == "failed"
